### PR TITLE
Error querying metadata for supported tokens

### LINKED ISSUE #1674: Error querying metadata for supported tokens
### Actual behavior

```
{
  "error": true,
  "message": "Server error: Cannot destructure property 'data' of '(intermediate value)' as it is undefined."
}
```

### Expected behavior

```
{
  "data": [],
  "meta": {}
}
```

### Steps to reproduce

- Query for supported tokens metadata with a chainID that doesn't below to the current network
  - https://betanet-service.lisk.com/api/v3/blockchain/apps/meta/tokens/supported?chainID=03000000

### Which version(s) does this affect? (Environment, OS, etc...)

v0.7.0-beta.1

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1674 

### How was it solved?
- [x] Added Exception handling

### How was it tested?
- [x] Local

### CODE REVIEW

File: services/blockchain-app-registry/shared/metadata.js [hunk 1]
```diff
@@ -381,14 +384,21 @@ const resolveTokenMetaInfo = async (tokenInfoFromDB) => {
...
+			if (response.data && response.data.supportedTokens) {
+				return Promise.resolve(response.data.supportedTokens);
+			}
+		} catch (err) {
+			logger.warn(err);
 
-		if (response.data && response.data.supportedTokens) {
-			return Promise.resolve(response.data.supportedTokens);
+			// eslint-disable-next-line no-continue
+			continue;
```
Comment (priojeetpriyom) [inline services/blockchain-app-registry/shared/metadata.js:398]: Can we safely remove this?

```suggestion
```

File: services/blockchain-app-registry/shared/metadata.js [hunk 2]
```diff
@@ -381,14 +384,21 @@ const resolveTokenMetaInfo = async (tokenInfoFromDB) => {
 const getSupportedTokensFromServiceURLs = async (serviceURLs) => {
 	for (let i = 0; i < serviceURLs.length; i++) {
 		const tokenSummaryEndpoint = `${serviceURLs[i].http}/api/v3/token/summary`;
-		// eslint-disable-next-line no-await-in-loop
-		const { data: response } = await HTTP.request(tokenSummaryEndpoint);
+		try {
+			// eslint-disable-next-line no-await-in-loop
+			const { data: response } = await HTTP.request(tokenSummaryEndpoint);
+
+			if (response.data && response.data.supportedTokens) {
```
Comment (priojeetpriyom) [inline services/blockchain-app-registry/shared/metadata.js:391]: Do we need the log? if not, then would it be better to update the checks so that it does not generate exception in first place as exception handling a bit costlier operation?

```suggestion
			const response = await HTTP.request(tokenSummaryEndpoint);

			if (!response || !response.data || !response.data.data) continue;
			if (response.data.data.supportedTokens) {
```

File: services/blockchain-app-registry/shared/metadata.js [hunk 3]
```diff
@@ -381,14 +384,21 @@ const resolveTokenMetaInfo = async (tokenInfoFromDB) => {
...
+				return Promise.resolve(response.data.supportedTokens);
+			}
+		} catch (err) {
+			logger.warn(err);
```
Comment (priojeetpriyom) [inline services/blockchain-app-registry/shared/metadata.js:395]: incase we need the log, do we need to add the `err.stack` to the log?

**Review by priojeetpriyom — APPROVED** [review]

File: services/blockchain-app-registry/shared/metadata.js [hunk 4]
```diff
@@ -382,13 +385,13 @@ const getSupportedTokensFromServiceURLs = async (serviceURLs) => {
...
+		const response = await HTTP.request(tokenSummaryEndpoint);
 
-		if (response.data && response.data.supportedTokens) {
-			return Promise.resolve(response.data.supportedTokens);
+		if (response && response.data && response.data.data && response.data.data.supportedTokens) {
+			return Promise.resolve(response.data.data.supportedTokens);
 		}
 	}
-	return Promise.resolve({});
+	return Promise.reject(new Error('Failed to retrieve supported tokens from service URLs'));
```
Comment (nagdahimanshu) [inline services/blockchain-app-registry/shared/metadata.js:394]:
```suggestion
	return Promise.reject(new Error('Failed to retrieve supported tokens from service URLs.'));
```

File: services/blockchain-app-registry/shared/metadata.js [hunk 5]
```diff
@@ -455,22 +458,27 @@ const getBlockchainAppsTokensSupportedMetadata = async (params) => {
...
+		tokenMetadata.meta = {
+			count: tokensMeta.length,
+			offset,
+			total,
+		};
 
-	return tokenMetadata;
+		return tokenMetadata;
+	} catch (err) {
+		logger.error(err.stack);
```
Comment (nagdahimanshu) [inline services/blockchain-app-registry/shared/metadata.js:479]: Should we change log level to `warn` here?

**Review by nagdahimanshu — APPROVED** [review]
LGTM 👍
