### PR TITLE
Unable to query pending transactions by address

### LINKED ISSUE #1712: Unable to query pending transactions by address
### Actual behavior
Querying pending transactions by address returns empty array even if the transaction exists in pool.

### Expected behavior
Querying pending transactions by all supported parameters should work and return proper response

### Steps to reproduce
Invoke: `/api/v3/transactions?executionStatus=pending&address='sender or recipient address of transaction in a pool'` endpoint.

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Service v0.7.0-beta.1

### PR DESCRIPTION
**Pull request by nagdahimanshu**
### What was the problem?
This PR resolves #1712 #1713 

### How was it solved?

- [x] Fix logic to query pending transactions by address
- [x] Refresh validators cache on every change commission transaction

### How was it tested?
Local
- docker
- debugger

### CODE REVIEW

File: services/blockchain-indexer/shared/dataService/pos/validators.js [hunk 1]
```diff
@@ -261,7 +261,8 @@ const updateValidatorListEveryBlock = () => {
 			if (block && block.transactions && Array.isArray(block.transactions)) {
 				block.transactions.forEach(tx => {
 					if (tx.module === MODULE.POS) {
-						if (tx.command === COMMAND.REGISTER_VALIDATOR) {
+						if (tx.command === COMMAND.REGISTER_VALIDATOR
+							|| tx.command === COMMAND.CHANGE_COMMISSION) {
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/pos/validators.js:265]: Alternative way of writing,

```suggestion
						if ([COMMAND.REGISTER_VALIDATOR, COMMAND.CHANGE_COMMISSION].includes(tx.command)) {
```

**Review by sameersubudhi — APPROVED** [review]
LGTM 👍

**Review by priojeetpriyom — APPROVED** [review]

**Review by priojeetpriyom — APPROVED** [review]
