### PR TITLE
Connector creates too many ws connections with the node which stresses out the node

### LINKED ISSUE #1978: Connector creates too many ws connections with the node which stresses out the node
### Actual behavior
Connector forcefully re-instantiates connection with the node many times and can establish many ws connections in short period of time during indexing genesis block which stresses out the node

### Expected behavior
Connector should not stress out the node.

### Steps to reproduce
Start Lisk service in pm2 or docker

### Which version(s) does this affect? (Environment, OS, etc...)
`0.7.1`

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1978

### How was it solved?
- [x] Updated node liveliness check mechanism

### How was it tested?
Local

### CODE REVIEW

**Review by sameersubudhi — APPROVED** [review]
LGTM 👍

File: services/blockchain-connector/shared/sdk/client.js [hunk 1]
```diff
@@ -162,13 +165,38 @@ if (config.isUseLiskIPCClient) {
...
+		if (
+			!isGenesisBlockIndexed &&
+			indexStatus.data &&
+			indexStatus.data.genesisHeight <= indexStatus.data.lastIndexedBlockHeight
+		) {
+			clearInterval(intervalTimeout);
+			triggerRegularClientLivelinessChecks(CLIENT_ALIVE_ASSUMPTION_TIME);
+			isGenesisBlockIndexed = true;
+			logger.info(
+				`API client heartbeat checks re-scheduled to run every ${CLIENT_ALIVE_ASSUMPTION_TIME_BEFORE_GENESIS}ms.`,
```
Comment (sameersubudhi) [inline services/blockchain-connector/shared/sdk/client.js:193]:
```suggestion
				`API client heartbeat checks re-scheduled to run every ${CLIENT_ALIVE_ASSUMPTION_TIME}ms.`,
```

**Review by priojeetpriyom — APPROVED** [review]
