### PR TITLE
Incorrect information in new.block event payload

### LINKED ISSUE #1930: Incorrect information in new.block event payload
### Actual behavior

`numberOfTransactions` in the `new.block` event payload doesn't match the actual value. Also, the `new.transactions` event is not emitted.

`new.block` event payload:
```
====== new.block ======
{
  "data": [
    {
      "id": "01f63f19490351011adb81e5e9b4e1d1711a93d77ccbe1485ba3a087650417e6",
      "version": 2,
      "timestamp": 1700151600,
      "height": 20621870,
      "previousBlockID": "881391014804c4b202b6f8e75e26255643807afcdf8f4713ce3e85562c0ca06c",
      "generator": {
        "address": "lsks3nfpf5bt6xa5qo73ftgaersg89t8fx5ov9d9z",
        "name": "gr33ndrag0n",
        "publicKey": "961d1a1057a09f865291873e9ba3d0af7b2a3a1e971bb7576a2aab1c526acbcd"
      },
      "transactionRoot": "f9b0fba4431fbaee7bbd39a0ed19c41b427afd2cd4211500f0e05fcbd09368c1",
      "assetRoot": "f4844a91baaf797680904726c9eec9c2cd6cc051e41eb48495113cf8536b1f2f",
      "stateRoot": "f66595f65e25d664d32e65deaa5a0ddfbe6ae14876b40dc232bcfa89928d9b9e",
      "eventRoot": "d54211c72d08104c03358df4ba2af961bc7ca3e1ec308ee2519130002e9c297f",
      "maxHeightPrevoted": 20621778,
      "maxHeightGenerated": 20621778,
      "validatorsHash": "c19c71b3c306e3ee928baf26a01463b8cd2dd1e38799336e75484c6f48c1356e",
      "aggregateCommit": {
        "height": 20621699,
        "aggregationBits": "",
        "certificateSignature": ""
      },
      "numberOfTransactions": 0,
      "numberOfAssets": 0,
      "numberOfEvents": 9,
      "totalForged": "918511027",
      "totalBurnt": "0",
      "networkFee": "0",
      "signature": "8a5e8ff5b47d599848c3dbf9dae3259c6ceace7cad16e6c1aaddc4e1263d26820a565aece36e3fce0040ed878cb4f714d5498d499263f02d7acc401565bcb308",
      "reward": "918511027",
      "isFinal": false
    }
  ],
  "meta": {
    "count": 1,
    "offset": 0,
    "total": 172455
  }
}
```

Blocks endpoint response for the same block: https://testnet-service.lisk.com/api/v3/blocks?blockID=01f63f19490351011adb81e5e9b4e1d1711a93d77ccbe1485ba3a087650417e6
```
{
  "data": [
    {
      "id": "01f63f19490351011adb81e5e9b4e1d1711a93d77ccbe1485ba3a087650417e6",
      "version": 2,
      "timestamp": 1700151600,
      "height": 20621870,
      "previousBlockID": "881391014804c4b202b6f8e75e26255643807afcdf8f4713ce3e85562c0ca06c",
      "generator": {
        "address": "lsks3nfpf5bt6xa5qo73ftgaersg89t8fx5ov9d9z",
        "name": "gr33ndrag0n",
        "publicKey": "961d1a1057a09f865291873e9ba3d0af7b2a3a1e971bb7576a2aab1c526acbcd"
      },
      "transactionRoot": "f9b0fba4431fbaee7bbd39a0ed19c41b427afd2cd4211500f0e05fcbd09368c1",
      "assetRoot": "f4844a91baaf797680904726c9eec9c2cd6cc051e41eb48495113cf8536b1f2f",
      "stateRoot": "f66595f65e25d664d32e65deaa5a0ddfbe6ae14876b40dc232bcfa89928d9b9e",
      "eventRoot": "d54211c72d08104c03358df4ba2af961bc7ca3e1ec308ee2519130002e9c297f",
      "maxHeightPrevoted": 20621778,
      "maxHeightGenerated": 20621778,
      "validatorsHash": "c19c71b3c306e3ee928baf26a01463b8cd2dd1e38799336e75484c6f48c1356e",
      "aggregateCommit": {
        "height": 20621699,
        "aggregationBits": "",
        "certificateSignature": ""
      },
      "numberOfTransactions": 1,
      "numberOfAssets": 1,
      "numberOfEvents": 9,
      "totalForged": "918661027",
      "totalBurnt": "150000",
      "networkFee": "0",
      "signature": "8a5e8ff5b47d599848c3dbf9dae3259c6ceace7cad16e6c1aaddc4e1263d26820a565aece36e3fce0040ed878cb4f714d5498d499263f02d7acc401565bcb308",
      "reward": "918511027",
      "isFinal": false
    }
  ],
  "meta": {
    "count": 1,
    "offset": 0,
    "total": 1
  }
}
```

### Expected behavior

The block in the event payload must match the endpoint response.

### Steps to reproduce

- Post a transaction
- Track the `new.block` and `new.transactions` WS events
- Query the block containing the transaction via the endpoint

### Which version(s) does this affect? (Environment, OS, etc...)

v0.7.0-rc.4

### PR DESCRIPTION
**Pull request by priojeetpriyom**
### What was the problem?

This PR resolves #1930 

### How was it solved?

- [x] Fetch transactions by blockID before formatting to generate `numberOfTransactions`
- [x] Use processed transactions as transactions payload instead of querying node
 
### How was it tested?
 - [x] Local

### CODE REVIEW

File: services/blockchain-indexer/shared/messageProcessor.js [hunk 1]
```diff
@@ -77,8 +78,10 @@ const initQueueStatus = async () => {
 
 const newBlockProcessor = async header => {
 	logger.debug(`New block (${header.id}) received at height ${header.height}.`);
-	const response = await formatBlock(header);
+	const { data: transactions } = await getTransactionsByBlockID(header.id);
```
Comment (vardan10) [inline services/blockchain-indexer/shared/messageProcessor.js:81]: Should we fetch `assets` as well? Since even `numberOfAssets` are inconsistent https://github.com/LiskHQ/lisk-service/issues/1930
If not maybe we can remove `numberOfAssets` from new block events?

Comment (sameersubudhi) [reply services/blockchain-indexer/shared/messageProcessor.js:81]: I'd also recommend to further optimize this. Do not make a call if the `transactionRoot` from the event payload matches the empty payload hash.

Let's discuss this offline whenever you're available.

Comment (priojeetpriyom) [reply services/blockchain-indexer/shared/messageProcessor.js]: Applied.

**Review by sameersubudhi — APPROVED** [review]

**Review by vardan10 — APPROVED** [review]
