### PR TITLE
app-registry crashes on metadata repository updates

### LINKED ISSUE #1461: app-registry crashes on metadata repository updates
### Actual behavior

Running Lisk Service (blockchain-app-registry) and updating the metadata registry crashes the application with the following error:

```
2023-01-25 09:16:55 719: [Error: ENOENT: no such file or directory, open '/root/lisk-service/services/blockchain-app-registry/data/app-registry/alphanet/Enevti/app.json'] {
2023-01-25 09:16:55 719:   errno: -2,
2023-01-25 09:16:55 719:   code: 'ENOENT',
2023-01-25 09:16:55 719:   syscall: 'open',
2023-01-25 09:16:55 719:   path: '/root/lisk-service/services/blockchain-app-registry/data/app-registry/alphanet/Enevti/app.json'
2023-01-25 09:16:55 719: }
```

### Expected behavior
- Repository re-sync mechanism should work flawlessly and not crash the application.
- Application should have proper error handling.

### Steps to reproduce
- Start Lisk Service
- Make changes to the app-registry repo
- Wait for the repo resync job to kick in at the 10th minute

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Service `feature/1157-prepare-lisk-service-v070-for-beta` branch

### PR DESCRIPTION
**Pull request by priojeetpriyom**
### What was the problem?
This PR resolves #1461 

### How was it solved?
- [x] Debug and fix app-registry crash when
    - [x] File is added on remote
    - [x] File is update on remote
    - [x] File is deleted on remote
- [x] Update db on remote file deletion and update.
    - [x] File is deleted on remote
    - [x] File is updated on remote
- [x] Add test for `rm` method

### How was it tested?
- [x] Local
- [ ] /blockchain/apps/meta endpoint should work without error

### Steps before merge
- [ ] delete `temp` branch from app-registry: https://github.com/LiskHQ/app-registry/branches

### CODE REVIEW

File: services/blockchain-app-registry/shared/metadataIndex.js [hunk 1]
```diff
@@ -124,6 +124,70 @@ const indexMetadataFromFile = async (network, app, filename = null, dbTrx) => {
...
+			chainName: chainMeta.chainName,
+			network,
+		};
+
+		logger.debug(`Deleting tokens information for the app: ${app} (${network}).`);
+		await deleteTokensMeta(tokenMeta, dbTrx);
+		logger.debug(`Deleted tokens information for the app: ${app} (${network}).`);
+	}
+	logger.info(`Finished Deleting metadata information for the app: ${app} (${network}).`);
+};
```
Comment (priojeetpriyom) [inline services/blockchain-app-registry/shared/metadataIndex.js:189]: followed same logical flow as `indexMetadataFromFile`.

File: services/blockchain-app-registry/shared/utils/downloadUtils.js [hunk 2]
```diff
@@ -57,21 +59,24 @@ const downloadFile = (url, filePath) => new Promise((resolve, reject) => {
...
+					logger.info('File downloaded successfully.');
+					setTimeout(resolve, 100); // Since the promise resolves earlier than expected
+				});
+			} else {
+				const errMessage = `Download failed with HTTP status code: ${response.statusCode} (${response.statusMessage}).`;
+				logger.error(errMessage);
+				if (response.statusCode === 404) reject(new NotFoundException(errMessage));
+				reject(new Error(errMessage));
+			}
+		});
```
Comment (priojeetpriyom) [inline services/blockchain-app-registry/shared/utils/downloadUtils.js:79]: download logic is unchanged, only wrapped with a then listener.

File: services/blockchain-app-registry/shared/metadataIndex.js [hunk 3]
```diff
@@ -157,7 +221,7 @@ const indexAllBlockchainAppsMeta = async () => {
 									logger.debug('Committed MySQL transaction to index blockchain metadata information.');
 								} catch (error) {
 									await rollbackDbTransaction(dbTrx);
-									logger.debug(`Rolled back MySQL transaction to index blockchain metadata information.\nError: ${error}`);
+									logger.debug(`Rolled back MySQL transaction to index blockchain metadata information.\nError: ${error}.`);
```
Comment (sameersubudhi) [inline services/blockchain-app-registry/shared/metadataIndex.js:224]:
```suggestion
									logger.debug(`Rolled back MySQL transaction to index blockchain metadata information.\nError: ${error}`);
```

File: services/blockchain-app-registry/shared/utils/downloadRepository.js [hunk 4]
```diff
@@ -188,40 +202,65 @@ const syncWithRemoteRepo = async () => {
 		const { lastSyncedCommitHash, latestCommitHash } = await getCommitInfo();
 
 		if (lastSyncedCommitHash === latestCommitHash) {
-			logger.info('Database is already up-to-date');
+			logger.info('Database is already up-to-date.');
 		} else {
 			const diffInfo = await getDiff(lastSyncedCommitHash, latestCommitHash);
 			// TODO: Add a check to filter out non-blockchain apps related files
```
Comment (sameersubudhi) [inline services/blockchain-app-registry/shared/utils/downloadRepository.js:208]: Can we also please address this TODO?

File: services/blockchain-app-registry/shared/utils/downloadRepository.js [hunk 5]
```diff
@@ -188,40 +202,65 @@ const syncWithRemoteRepo = async () => {
...
-			const filesChanged = diffInfo.data.files.map(file => file.filename);
+			// Sorting is necessary to ensure app.json is downloaded before nativetokens.json file
+			// Otherwise the indexing may fail as token metadata indexing is dependant on app metadata
+			const modifiedFiles = diffInfo.data.files.sort();
```
Comment (sameersubudhi) [inline services/blockchain-app-registry/shared/utils/downloadRepository.js:211]: This implementation is incorrect and won't achieve the intended effect (as specified in the comments), since `diffInfo.data.files` will be a list of object(s).
Also, sorting/non-sorting won't make a difference because of `concurrency: modifiedFiles.length` in BluebirdPromise.map. All the files will be processed asynchronously and they kickoff simultaneously.

File: services/blockchain-app-registry/shared/utils/downloadRepository.js [hunk 6]
```diff
@@ -188,40 +202,65 @@ const syncWithRemoteRepo = async () => {
...
+
+					// Delete indexed information if a meta file is updated/deleted
+					if (isMetadataFile(remoteFilePath) && fileUpdatedStatuses.includes(modifiedFile.status)) {
+						const [network, appName, filename] = remoteFilePath.split('/').slice(-3);
+						await deleteIndexedMetadataOfFile(network, appName, filename);
+					}
+
+					// Skip download and indexing for deleted file
+					if (modifiedFile.status === GITHUB_FILE_STATUS.REMOVED) {
+						rmdir(localFilePath, { recursive: false });
```
Comment (sameersubudhi) [inline services/blockchain-app-registry/shared/utils/downloadRepository.js:233]:
```suggestion
						await rmdir(localFilePath, { recursive: false });
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/blockchain-app-registry/shared/metadataIndex.js (hunk 3 above)
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/metadataIndex.js]: Applied.

File: services/blockchain-app-registry/shared/metadataIndex.js [hunk 7]
```diff
@@ -124,6 +124,70 @@ const indexMetadataFromFile = async (network, app, filename = null, dbTrx) => {
...
+				chainName: tokenMeta.chainName,
+				localID,
+			};
+			await tokenMetadataTable.delete(queryParams, dbTrx);
+		},
+		{ concurrency: tokenMeta.localIDs.length },
+	);
+};
+
+const deleteIndexedMetadataOfFile = async (network, app, filename = null, dbTrx) => {
```
[the remark this answers is not in the document]
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/metadataIndex.js]: Applied.

File: services/blockchain-app-registry/shared/utils/downloadUtils.js [hunk 8]
```diff
@@ -57,21 +59,24 @@ const downloadFile = (url, filePath) => new Promise((resolve, reject) => {
...
-				setTimeout(resolve, 100); // Since the promise resolves earlier than expected
-			});
-		} else {
-			const errMessage = `Download failed with HTTP status code: ${response.statusCode} (${response.statusMessage})`;
-			logger.error(errMessage);
-			if (response.statusCode === 404) reject(new NotFoundException(errMessage));
-			reject(new Error(errMessage));
-		}
+	const dirPath = path.dirname(filePath);
+	mkdir(dirPath, { recursive: true }).then(() => {
```
[the remark this answers is not in the document]
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/utils/downloadUtils.js]: okay. will move folder creation under the `syncWithRemoteRepo` method.

File: services/blockchain-app-registry/shared/utils/downloadRepository.js (hunk 6 above)
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/utils/downloadRepository.js]: Applied.

File: services/blockchain-app-registry/shared/utils/fsUtils.js [hunk 9]
```diff
@@ -71,6 +71,10 @@ const rmdir = async (directoryPath, options = { recursive: true }) => new Promis
 	);
 });
 
+const rmdir = async (directoryPath, options = { recursive: true }) => (
+	rm(directoryPath, { ...options, recursive: true })
+);
```
Comment (sameersubudhi) [inline services/blockchain-app-registry/shared/utils/fsUtils.js:76]: We aren't awaiting the `rm` invocation. Also, could you please add a couple of tests for the `rm` method.

```suggestion
const rmdir = async (directoryPath, options) => rm(directoryPath, { ...options, recursive: true });
```
or
```suggestion
const rmdir = async (directoryPath, options) => rm(
	directoryPath,
	{ ...options, recursive: true },
);
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/blockchain-app-registry/shared/utils/downloadRepository.js (hunk 5 above)
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/utils/downloadRepository.js]: Applied.

File: services/blockchain-app-registry/shared/utils/fsUtils.js (hunk 9 above)
Comment (sameersubudhi) [reply services/blockchain-app-registry/shared/utils/fsUtils.js]: The returned promise was from `rmdir` but the promise from `rm` wasn't awaited since that promise wasn't returned by `rmdir`.

File: services/blockchain-app-registry/shared/utils/fsUtils.js [hunk 10]
```diff
@@ -20,130 +20,169 @@ const { Logger } = require('lisk-service-framework');
...
 
-			logger.debug(`Successfully removed directory: ${directoryPath}`);
+			logger.debug(`Successfully removed file/directory: ${deletePath}`);
 			return resolve(true);
 		},
 	);
 });
 
-const read = (filePath) => new Promise((resolve, reject) => {
+const rmdir = async (directoryPath, options = { recursive: true }) => rm(
```
[the remark this answers is not in the document]
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/utils/fsUtils.js]: Applied.

**Review by nagdahimanshu — APPROVED** [review]
LGTM and works as expected 👍

File: services/blockchain-app-registry/shared/utils/downloadRepository.js [hunk 11]
```diff
@@ -180,48 +197,149 @@ const buildEventPayload = async (allFilesModified) => {
...
+		await BluebirdPromise.map(
+			Object.keys(groupedFiles),
+			async (networkName) => {
+				const appsInNetwork = groupedFiles[networkName];
+
+				await BluebirdPromise.map(
+					Object.keys(appsInNetwork),
+					async (appName) => {
+						const appFiles = appsInNetwork[appName];
+						const dbTrx = await startDbTransaction(connection);
```
Comment (sameersubudhi) [inline services/blockchain-app-registry/shared/utils/downloadRepository.js:278]: Let's use only one DB connction at the top level. Is there a reason because of which we a connection per network? Also, how do we handle the failure scenario (in case a transaction fails)?

Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/utils/downloadRepository.js:287]: Discussed offline

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

**Comment by sameersubudhi** [comment]
Additionally, please check and add unit testcases if we can increase the code coverage.

File: services/blockchain-app-registry/shared/metadataIndex.js [hunk 12]
```diff
@@ -89,16 +89,24 @@ const indexChainMeta = async (chainMeta, dbTrx) => {
 	await applicationMetadataTable.upsert(chainMetaToIndex, dbTrx);
 };
 
-const indexMetadataFromFile = async (network, app, filename = null, dbTrx) => {
-	const { dataDir } = config;
-	const repo = config.gitHub.appRegistryRepoName;
-	logger.debug(`Indexing metadata information for the app: ${app} (${network}).`);
+// Given filepath of app.json or nativetokens.json, indexes the information in DB
```
[the remark this answers is not in the document]
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/metadataIndex.js:92]: I would prefer to keep the comment.

File: services/blockchain-app-registry/shared/utils/downloadRepository.js [hunk 13]
```diff
@@ -180,48 +197,178 @@ const buildEventPayload = async (allFilesModified) => {
...
+						// Move downloaded files
+						await BluebirdPromise.map(
+							filesToBeMoved,
+							async (filePathInfo) => {
+								// Create directory to move file
+								await mkdir(path.dirname(filePathInfo.to));
+								await rename(filePathInfo.from, filePathInfo.to);
+							},
+							{ concurrency: filesToBeMoved.length },
+						);
```
[the remark this answers is not in the document]
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/utils/downloadRepository.js:350]: > I think, we can directly move (or overwrite existing) files instead of deleting them. Only delete the ones that have the status GITHUB_FILE_STATUS.REMOVED.

Actually we are doing this currently.

> Create an alias mv

Applied.

File: services/blockchain-app-registry/shared/utils/downloadRepository.js [hunk 14]
```diff
@@ -180,48 +197,178 @@ const buildEventPayload = async (allFilesModified) => {
...
+								continue;
+							}
+
+							// Create directory and download latest file
+							const tempFilePath = path.join(tempDownloadDir, remoteFilePath);
+							const dirPath = path.dirname(tempFilePath);
+							await mkdir(dirPath, { recursive: true });
+
+							const result = await getFileDownloadURL(remoteFilePath);
+							await downloadFile(result.data.download_url, tempFilePath);
```
[the remark this answers is not in the document]
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/utils/downloadRepository.js:318]: Applied.

File: services/blockchain-app-registry/shared/metadataIndex.js [hunk 15]
```diff
@@ -121,7 +129,70 @@ const indexMetadataFromFile = async (network, app, filename = null, dbTrx) => {
...
+	if (!network || !app) throw Error('Require both \'network\' and \'app\'.');
+
+	const appPathInClonedRepo = path.dirname(filePath);
+	logger.trace('Reading chain information.');
+	const chainMetaString = await read(`${appPathInClonedRepo}/${FILENAME.APP_JSON}`);
+	const chainMeta = { ...JSON.parse(chainMetaString) };
+
+	if (filename === FILENAME.APP_JSON || filename === null) {
+		logger.debug(`Deleting chain information for the app: ${app} (${network}).`);
+		await deleteChainMeta(chainMeta, dbTrx);
```
[the remark this answers is not in the document]
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/metadataIndex.js:174]: Renamed indexing methods and `/blockchain/apps/meta` variables as well.

File: services/blockchain-app-registry/shared/utils/downloadRepository.js [hunk 16]
```diff
@@ -180,48 +197,178 @@ const buildEventPayload = async (allFilesModified) => {
...
+							{ concurrency: filesToBeMoved.length },
+						);
+					},
+					{ concurrency: Object.keys(appsInNetwork).length },
+				);
+			},
+			{ concurrency: Object.keys(groupedFiles).length },
+		);
+
+		await keyValueTable.set(KV_STORE_KEY.COMMIT_HASH_UNTIL_LAST_SYNC, latestCommitHash);
```
[the remark this answers is not in the document]
Comment (priojeetpriyom) [reply services/blockchain-app-registry/shared/utils/downloadRepository.js]: Applied.

File: services/blockchain-app-registry/shared/metadataIndex.js [hunk 17]
```diff
@@ -75,53 +75,124 @@ const indexTokensMeta = async (tokenMeta, dbTrx) => {
...
+			localIDs,
+			chainName: appMeta.chainName,
+			network,
+		};
+
+		logger.debug(`Deleting tokens information for the app: ${app} (${network}).`);
+		await deleteTokensMeta(tokenMeta, dbTrx);
+		logger.debug(`Deleted tokens information for the app: ${app} (${network}).`);
+	}
+	logger.info(`Finished Deleting metadata information for the app: ${app} (${network}) filename: ${filename}.`);
```
Comment (sameersubudhi) [inline services/blockchain-app-registry/shared/metadataIndex.js:195]:
```suggestion
	logger.info(`Finished deleting metadata information for the app: ${app} (${network}) file: ${filename}.`);
```

File: services/blockchain-app-registry/tests/functional/shared/utils/downloadRepository.test.js [hunk 18]
```diff
@@ -21,7 +21,7 @@ const {
 	getRepoDownloadURL,
 	getLatestCommitHash,
 	getCommitInfo,
-	getFileDownloadURL,
+	getFileDownloadUrl,
```
Comment (sameersubudhi) [inline services/blockchain-app-registry/tests/functional/shared/utils/downloadRepository.test.js:24]: Since `URL` is an abbreviation.
```suggestion
	getFileDownloadURL,
```

Comment (priojeetpriyom) [reply services/blockchain-app-registry/tests/functional/shared/utils/downloadRepository.test.js]: Applied.

File: services/blockchain-app-registry/tests/functional/shared/utils/downloadRepository.test.js [hunk 19]
```diff
@@ -72,8 +72,8 @@ describe('Test getFileDownloadURL method', () => {
 	it('should return correct file download info when file is valid', async () => {
 		/* eslint-disable-next-line no-useless-escape */
 		const fileUrlRegex = new RegExp(`^https:\/\/\\w*.github.com\/repos\/LiskHQ\/${config.gitHub.appRegistryRepoName}\/contents\/devnet\/Enevti\/nativetokens.json\\?owner=LiskHQ&repo=${config.gitHub.appRegistryRepoName}&ref=${config.gitHub.branch}$`);
```
Comment (sameersubudhi) [inline services/blockchain-app-registry/tests/functional/shared/utils/downloadRepository.test.js:74]: There's no need for a regular expression here. It can be a simple string expression.
And, `expect(response).toMatch(fileUrlRegex);` can simply be replaced by `expect(response).toBe(expectedFileURL);`.

Comment (priojeetpriyom) [reply services/blockchain-app-registry/tests/functional/shared/utils/downloadRepository.test.js]: Discussed offline.

**Comment by sameersubudhi** [comment]
@priojeetpriyom Could you please add unit tests for `getModifiedFileNames` in `services/blockchain-app-registry/shared/utils/downloadRepository.js`?

**Review by sameersubudhi — APPROVED** [review]
