### PR TITLE
Indexer queries for block heights in future

### LINKED ISSUE #1980: Indexer queries for block heights in future
### Actual behavior

```
2023-12-07T10:33:33.162 INFO [generators] Updated generators list with 101 validators.
2023-12-07T10:33:33.171 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.172 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:33.179 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.180 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:33.198 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.199 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:33.205 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.206 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:33.211 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.212 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:33.217 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.218 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:33.222 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.223 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:33.228 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.228 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:33.233 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.234 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:33.239 ERROR [microservice] Error occurred! Specified key 0401651ab9 does not exist
2023-12-07T10:33:33.239 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:37.794 INFO [accountBalanceIndex] Updated account balance for 1 account(s).
2023-12-07T10:33:37.794 INFO [updateAccounts] Triggered account balance updates successfully.
2023-12-07T10:33:41.472 INFO [indexStatus] currentChainHeight: 23403193, lastIndexedBlockHeight: 23403192
2023-12-07T10:33:41.472 INFO [indexStatus] Block index status: 12201/12202 blocks indexed (99.99%).
2023-12-07T10:33:42.949 INFO [blockchainIndex] Scheduling indexing of new block: 80bd44df3b7423562e909262f1bd8c6466c12c018d0074048c9ab381e52dc456 at height 23403193.
2023-12-07T10:33:42.956 INFO [messageProcessor] Finished scheduling new block (80bd44df3b7423562e909262f1bd8c6466c12c018d0074048c9ab381e52dc456) event for the block at height 23403193.
2023-12-07T10:33:42.960 INFO [pendingTransactions] Updated pending transaction cache with 0 transactions.
2023-12-07T10:33:42.961 INFO [blockchainIndex] Scheduling indexing of new block: 80bd44df3b7423562e909262f1bd8c6466c12c018d0074048c9ab381e52dc456 at height 23403193.
2023-12-07T10:33:42.963 INFO [messageProcessor] Finished scheduling new block (80bd44df3b7423562e909262f1bd8c6466c12c018d0074048c9ab381e52dc456) event for the block at height 23403193.
2023-12-07T10:33:42.990 INFO [pendingTransactions] Updated pending transaction cache with 0 transactions.
2023-12-07T10:33:43.044 INFO [generators] Updated generators list with 101 validators.
2023-12-07T10:33:43.050 INFO [generators] Updated generators list with 101 validators.
2023-12-07T10:33:43.058 INFO [blockchainIndex] Scheduling indexing of new block: 80bd44df3b7423562e909262f1bd8c6466c12c018d0074048c9ab381e52dc456 at height 23403193.
2023-12-07T10:33:43.063 INFO [messageProcessor] Finished scheduling new block (80bd44df3b7423562e909262f1bd8c6466c12c018d0074048c9ab381e52dc456) event for the block at height 23403193.
2023-12-07T10:33:43.064 INFO [pendingTransactions] Updated pending transaction cache with 0 transactions.
2023-12-07T10:33:43.075 INFO [blockchainIndex] Successfully indexed block 80bd44df3b7423562e909262f1bd8c6466c12c018d0074048c9ab381e52dc456 at height 23403193.
2023-12-07T10:33:43.117 INFO [generators] Updated generators list with 101 validators.
2023-12-07T10:33:43.125 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.126 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:43.134 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.143 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:43.150 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.151 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:43.156 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.157 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:43.162 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.162 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:43.168 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.169 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:43.174 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.175 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:43.180 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.181 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:43.185 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.186 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
2023-12-07T10:33:43.191 ERROR [microservice] Error occurred! Specified key 0401651aba does not exist
2023-12-07T10:33:43.192 WARN [queue] IndexBlocks job failed with error: Cannot read properties of undefined (reading 'height').
```

### Expected behavior

Indexer shouldn't query for block at heights which do not exist.

### Steps to reproduce

- Run LS against the mainnet and observe

### Which version(s) does this affect? (Environment, OS, etc...)

v0.7.1

### Additional Information

The connector seems to register duplicate listeners for the same event, which causes this issue:

```
2023-12-07T10:17:53.697 INFO [allEvents] Received chain_newBlock event, dispatching chainNewBlock signal (id: 3d54f6ea42edcd2fc8535c857acf0036d79e9a6dcbe0c3d4d0448cd10c8c2ccd, height: 23403105).
2023-12-07T10:17:53.698 INFO [allEvents] Received chain_newBlock event, dispatching chainNewBlock signal (id: 3d54f6ea42edcd2fc8535c857acf0036d79e9a6dcbe0c3d4d0448cd10c8c2ccd, height: 23403105).
2023-12-07T10:17:53.698 INFO [allEvents] Received chain_newBlock event, dispatching chainNewBlock signal (id: 3d54f6ea42edcd2fc8535c857acf0036d79e9a6dcbe0c3d4d0448cd10c8c2ccd, height: 23403105).
2023-12-07T10:18:02.740 INFO [allEvents] Received chain_newBlock event, dispatching chainNewBlock signal (id: e9cee2c7612490c92feaa2512c3d02e7202981862a7257e6f0574890554b22cd, height: 23403106).
2023-12-07T10:18:02.741 INFO [allEvents] Received chain_newBlock event, dispatching chainNewBlock signal (id: e9cee2c7612490c92feaa2512c3d02e7202981862a7257e6f0574890554b22cd, height: 23403106).
2023-12-07T10:18:02.860 INFO [allEvents] Received chain_newBlock event, dispatching chainNewBlock signal (id: e9cee2c7612490c92feaa2512c3d02e7202981862a7257e6f0574890554b22cd, height: 23403106).
```

### PR DESCRIPTION
**Pull request by sameersubudhi**
### What was the problem?

This PR resolves #1980

### How was it solved?

- [x] Skip indexBlock job run if the height to be indexed does not exist
- [x] Improve instantiateClient implementation
- [x] Optimize triggerAccountsBalanceUpdate implementation
- [x] Fix getAllPosValidators implementation in connector
- [x] Include signatures in `/transactions` endpoint responses
- [x] Minor code refactor/improvements

### How was it tested?

Locally + Server (Docker/PM2)

### CODE REVIEW

**Review by vardan10 — APPROVED** [review]

File: services/blockchain-indexer/shared/indexer/accountBalanceIndex.js [hunk 1]
```diff
@@ -80,18 +80,23 @@ const triggerAccountsBalanceUpdate = async () => {
 		config.set.accountBalanceUpdate.batchSize,
 	);
 
+	const numAddressesScheduled = addresses.length;
 	try {
 		// eslint-disable-next-line no-restricted-syntax
-		for (const address of addresses) {
+		while (addresses.length) {
+			const address = addresses.shift();
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/indexer/accountBalanceIndex.js:87]:
```suggestion
			const address = addresses.pop();
```

Comment (sameersubudhi) [reply services/blockchain-indexer/shared/indexer/accountBalanceIndex.js:87]: I preferred using `shift` over `pop` to ensure FIFO. With `pop` it'd be `LIFO` and when the update fails we keep pushing the last address to the end of the list. So, using `pop` would then query for the same address for which the update had failed.

**Review by vardan10 — APPROVED** [review]
