### PR TITLE
Unable to query events

### LINKED ISSUE #1358: Unable to query events
### Actual behavior

Querying events results in no response and crashes the Gateway with the following error:

```
2022-11-23T14:49:00.674 ERROR [GATEWAY] <= ER_WRONG_FIELD_WITH_GROUP Request error: Error: select distinct `id`, `id` from `event_topics` where `timestamp` is not null and `index` is not null group by 1, 1 order by `timestamp` desc, `index` asc limit 10 - Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'lisk.event_topics.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by 
Error: select distinct `id`, `id` from `event_topics` where `timestamp` is not null and `index` is not null group by 1, 1 order by `timestamp` desc, `index` asc limit 10 - Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'lisk.event_topics.timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    at Packet.asError (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/sameer/Documents/Lisk/github/lisk-service/services/blockchain-indexer/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) 
Data: 
Request params: { limit: 10, sort: 'timestamp:desc', order: 'index:asc' } 
Request body: {}
Waiting for the debugger to disconnect...
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: ER_WRONG_FIELD_WITH_GROUP
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.writeHead (node:_http_server:275:11)
    at Service.onError (/Users/sameer/Documents/Lisk/github/lisk-service/services/gateway/app.js:123:9)
    at Service.sendError (/Users/sameer/Documents/Lisk/github/lisk-service/services/gateway/node_modules/moleculer-web/src/index.js:851:34)
    at Service.httpHandler (/Users/sameer/Documents/Lisk/github/lisk-service/services/gateway/shared/moleculer-web/methods.js:54:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}
```
### Expected behavior

Query for events must return response.

### Steps to reproduce

Invoke: `/api/v3/events` endpoint.

### Which version(s) does this affect? (Environment, OS, etc...)

Lisk Core `v4.0.0-alpha.4`
Lisk Service `v0.7.0-alpha.2`

### PR DESCRIPTION
**Pull request by sameersubudhi**
### What was the problem?
This PR resolves #1358 

### How was it solved?
- [x] Update nodeInfo cache immediately on chain events
- [x] Handle gateway errors gracefully to avoid application crash
- [x] Fix supported tokens implementation
- [x] Fix MySQL for distinct-based queries causing error when querying for events

### How was it tested?
Local against Lisk Core v4.0.0-alpha.4

### CODE REVIEW

File: services/blockchain-indexer/shared/dataService/business/events.js [hunk 1]
```diff
@@ -160,6 +161,8 @@ const getEvents = async (params) => {
 		{ concurrency: eventsInfo.length },
 	);
 
+	const total = await eventTopicsTable.count({ ...params, distinct: 'eventID' });
```
Comment (ManuGowda) [inline services/blockchain-indexer/shared/dataService/business/events.js:164]: point to discuss: why aren't we having SQL procedures?

**Review by ManuGowda — APPROVED** [review]
The changes looks fine, I have some points to discuss lets not merge until we discuss.
