### PR TITLE
SenderAddress also returns recipientAddress or generatorAddress in Events API

### LINKED ISSUE #1967: SenderAddress also returns recipientAddress or generatorAddress in Events API
### Actual behavior
SenderAddress also returns recipientAddress or generatorAddress in Events API

### Expected behavior
SenderAddress should not return recipientAddress or generatorAddress in Events API

### Steps to reproduce
Query the below 2 endpoints:
```
https://testnet-service.lisk.com/api/v3/events?senderAddress=lsk2447tv63fubjrqpkfn7e9e3zhhwnuhzyhmvhqw

https://testnet-service.lisk.com/api/v3/events?senderAddress=lskkmooceofx7tza3q5vr873mnmjxkrzgxo3hj36d&blockID=c36f44224c45b3aee18e44facaceab8fca548c877f73e6e59e0ba91911ff8ae1
```
### Which version(s) does this affect? (Environment, OS, etc...)
`0.7.0`

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1967 

### How was it solved?
- [x] Updated events API to use transactions ID for sender address query

### How was it tested?
Local

### CODE REVIEW

File: services/blockchain-connector/shared/sdk/client.js [hunk 1]
```diff
@@ -75,7 +75,8 @@ const checkIsClientAlive = async () =>
 		wsInstance.ping(() => {});
 
 		// eslint-disable-next-line consistent-return
-		setTimeout(() => {
+		const timeout = setTimeout(() => {
+			clearTimeout(timeout);
```
Comment (priojeetpriyom) [inline services/blockchain-connector/shared/sdk/client.js:79]: Do we need to clear timeout here? The timeout would invalid now as callback function is already executed after timing out.

**Review by priojeetpriyom — APPROVED** [review]

File: services/blockchain-connector/shared/sdk/client.js (hunk 1 above)
Comment (sameersubudhi) [reply services/blockchain-connector/shared/sdk/client.js:79]: It's unnecessary but a redundant measure we added based on my discussion with Ishan.

**Review by sameersubudhi — APPROVED** [review]
LGTM 👍

**Review by priojeetpriyom — APPROVED** [review]
