### PR TITLE
numberOfEvents missing in new block event payload

### LINKED ISSUE #1545: numberOfEvents missing in new block event payload
### Actual behavior

`numberOfEvents` and `reward` missing in new block event payload

```jsonc
{
  "data": [
    {
      "id": "52499413fef2651b71fb41890c0a00513f9e06875548cd482185e68fc6a7bc9f",
      "version": 2,
      "timestamp": 1679494860,
      "height": 43564,
      "previousBlockID": "a889e97b03b32432d135db25d0fff7a9a47251ddb0ed5c6d4d0a738f2ff72672",
      "generator": {
        "address": "lskguo9kqnea2zsfo3a6qppozsxsg92nuuma3p7ad",
        "name": "genesis_0",
        "publicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c"
      },
      "transactionRoot": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      "assetRoot": "33ae2e26a2691373f7cb6cd0092d29affe23344f48bb969c6f4db93163127fe9",
      "stateRoot": "d09b5a9b7ea6c5dbb85c73792346a098016a27c07cd53fb41c582d1d15590b0c",
      "maxHeightPrevoted": 43563,
      "maxHeightGenerated": 43563,
      "validatorsHash": "cc3b29510e3150c1ee7b0192dbe8947b07ce94b227fd3477b33c60c4a9203ff3",
      "aggregateCommit": {
        "height": 43562,
        "aggregationBits": "01",
        "certificateSignature": "806c4d4f1c62989bfba10aaae223b7ea4adec7dd212fa76f4230a4f34c359ae6e5f6dc602001243562ade369f828d7160e1c724b99e76dc70a9ee9434a066439188728003a03b89f2df165b425e53e86a2e8edffc865faba42a103c8c8f752ce"
      },
      "numberOfTransactions": 0,
      "numberOfAssets": 1,
      "totalForged": "0",
      "totalBurnt": "0",
      "networkFee": "0",
      "signature": "01dc33fd71ff2da8a3954fd08e5b1e73c7856a92c9bd67a9d5bb0f78caf79d8d0ee8c40dc77dc1b8c50da7932b2ca208e1f7d46f3cf9da4c42a312a97fa5f608",
      "isFinal": false
    }
  ],
  "meta": {
    "count": 1,
    "offset": 0,
    "total": 1
  }
}
```

### Expected behavior

The event payload should contain the `numberOfEvents` and `reward` fields in response and should exactly match the response structure from the `/blocks` endpoint.

### Steps to reproduce

- Subscribe to `new.block` event against a running instance of Lisk Service
 - Use: framework/bin/socket_io_subscribe_client.js

### Which version(s) does this affect? (Environment, OS, etc...)

Lisk Service v0.7.0-alpha.10

### PR DESCRIPTION
**Pull request by priojeetpriyom**
### What was the problem?
This PR resolves #1545 

### How was it solved?
- [x] Fetch events from connector if not available in db
- [x] Resolve block reward from events
- Update integration test schema for blocks
    - [x] Fix failing test
    - [x] Set minimum number of events to 1 as every block has atleast 1 event.
    - [x] Allow null for reward value as genesis block does not have reward event.

### How was it tested?
- [x] Local

### CODE REVIEW

File: services/blockchain-indexer/shared/dataService/business/blocks.js [hunk 1]
```diff
@@ -78,12 +78,33 @@ const normalizeBlock = async (originalBlock) => {
...
+
+			const events = await getEventsByHeight(block.height);
+			const blockRewardEvent = events.find(
+				e => [MODULE.REWARD, MODULE.DYNAMIC_REWARD].includes(e.module)
+					&& e.name === EVENT.REWARD_MINTED,
+			);
+
+			return {
+				numberOfEvents: events.length,
+				reward: blockRewardEvent ? blockRewardEvent.data.amount : undefined,
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/dataService/business/blocks.js:103]:
```suggestion
				reward: blockRewardEvent ? blockRewardEvent.data.amount : null,
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

**Review by sameersubudhi — APPROVED** [review]
LGTM 👍

**Review by vardan10 — APPROVED** [review]
