### PR TITLE
Redis OOM errors

### LINKED ISSUE #1919: Redis OOM errors
### Actual behavior

```
2023-11-14T08:52:41.415 ERROR [queue] AccountQueueByPublicKey job error,ReplyError: ERR Error running script (call to f_ff9c18634832b0b4115a19b4de5f4788a7cfbd4e): @user_script:30: @user_script: 30: -OOM command not allowed when used memory > 'maxmemory'.   
2023-11-14T08:52:41.419 ERROR [queue] DeleteIndexedBlocks job error,ReplyError: ERR Error running script (call to f_ff9c18634832b0b4115a19b4de5f4788a7cfbd4e): @user_script:30: @user_script: 30: -OOM command not allowed when used memory > 'maxmemory'.   
2023-11-14T08:52:41.419 ERROR [queue] AccountQueueByAddress job error,ReplyError: ERR Error running script (call to f_ff9c18634832b0b4115a19b4de5f4788a7cfbd4e): @user_script:30: @user_script: 30: -OOM command not allowed when used memory > 'maxmemory'.   
2023-11-14T08:52:41.420 ERROR [queue] IndexBlocks job error,ReplyError: ERR Error running script (call to f_ff9c18634832b0b4115a19b4de5f4788a7cfbd4e): @user_script:30: @user_script: 30: -OOM command not allowed when used memory > 'maxmemory'.   
/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^

ReplyError: EXECABORT Transaction discarded because of previous errors.
    at parseError (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'exec', args: [] },
  previousErrors: [
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'llen',
        args: [ 'queue-lisk-service-framework:AccountQueueByPublicKey:wait' ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'llen',
        args: [
          'queue-lisk-service-framework:AccountQueueByPublicKey:active'
        ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'zcard',
        args: [
          'queue-lisk-service-framework:AccountQueueByPublicKey:completed'
        ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'zcard',
        args: [
          'queue-lisk-service-framework:AccountQueueByPublicKey:failed'
        ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'zcard',
        args: [
          'queue-lisk-service-framework:AccountQueueByPublicKey:delayed'
        ]
      }
    },
    ReplyError: OOM command not allowed when used memory > 'maxmemory'.
        at parseError (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:179:12)
        at parseType (/home/lisk/lisk-service/blockchain-indexer/node_modules/redis-parser/lib/parser.js:302:14) {
      command: {
        name: 'llen',
        args: [
          'queue-lisk-service-framework:AccountQueueByPublicKey:paused'
        ]
      }
    }
  ]
}

Node.js v18.18.2
```

### Expected behavior

The errors shouldn't be occurring.

### Steps to reproduce

- Run Lisk Service against Lisk Core in docker containers
- This issue doesn't occur every time. It is currently occurring on 1 of many instances running LS against Lisk Core testnet.

### Which version(s) does this affect? (Environment, OS, etc...)

v0.7.0-rc.4

### PR DESCRIPTION
**Pull request by sameersubudhi**
### What was the problem?

This PR resolves #1919 

### How was it solved?

- [x] Fix getLiveIndexingJobCount to include deletedBlocksIndexing job count (RC for OOM)
- [x] Await when scheduling block deletion to be successfully added to the job queue
- [x] Fix topics mapping for relayerFeeProcessed event
- [x] Fix issues with client.js
- [x] Fix edgecase scenario handling when setting IndexVerifiedHeight
- [x] Decrease generatedBlocks count for the generator when handling deleted blocks

### How was it tested?

Locally against testnet

### CODE REVIEW

**Review by vardan10 — APPROVED** [review]

File: services/blockchain-coordinator/shared/scheduler.js [hunk 1]
```diff
@@ -263,9 +265,9 @@ const scheduleMissingBlocksIndexing = async () => {
 
 				if (result.length === 0) {
 					const lastIndexVerifiedHeight = await getIndexVerifiedHeight();
-					if (batchEndHeight === lastIndexVerifiedHeight + MAX_QUERY_RANGE) {
```
Comment (priojeetpriyom) [inline services/blockchain-coordinator/shared/scheduler.js:266]: `MAX_QUERY_RANGE` > `MAX_BLOCKS_TO_SCHEDULE`, so we will always have only 1 batch. The values needs adjustment.

**Review by priojeetpriyom — APPROVED** [review]

**Review by priojeetpriyom — APPROVED** [review]
