### PR TITLE
Integrate account knowledge

### LINKED ISSUE #1666: Integrate account knowledge
### Actual behavior

Currently, the logic to fetch offchain account knowledge information is not integrated in response for the `/token/balances/top` endpoint.

```
{
  "data": {
    "0200000000000000": [
      {
        "address": "lskzzw334cgd7cew5mb9bbayjmojbodgmw9pdym6p",
        "balance": 100000000000000,
        "knowledge": {}
      }
    ]
  },
  "meta": {
    "count": 1,
    "offset": 0,
    "total": 138
  }
}
```

### Expected behavior

The `knowledge` information should be included if the information is available.

### Steps to reproduce

- TODO

### Which version(s) does this affect? (Environment, OS, etc...)

v0.7.0-beta.1

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1666 

### How was it solved?
- [x] Added account knowledge logic
- [x] Integrated account knowledge into top balances endpoint
- [x] Added few unit tests for validators

### How was it tested?
- [x] Local

### CODE REVIEW

File: services/blockchain-indexer/shared/indexer/knownAccounts.js [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+			logger.warn(`ChainId does not exist in the database: ${chainID}.`);
+		}
+	} catch (err) {
+		logger.error(`Could not reload known accounts: ${err.message}`);
+	}
+};
+
+const init = () => {
+	reloadKnowledge();
+	setInterval(reloadKnowledge, knownExpireMiliseconds);
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/knownAccounts.js:75]: Let's set it as a moleculer job under `jobs/dataService` directory.

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/blockchain-indexer/shared/indexer/knownAccounts.js [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+};
+
+init();
```
[the remark this answers is not in the document]
Comment (vardan10) [reply services/blockchain-indexer/shared/indexer/knownAccounts.js]: Added a molecular job so no need to initialise in init.js

**Review by sameersubudhi — APPROVED** [review]

File: services/blockchain-indexer/shared/dataService/knownAccounts.js [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+};
+
+const resolveNetworkByChainID = (chainID) => {
+	const networkID = chainID.substring(0, LENGTH_NETWORK_ID);
+
+	const matchingNetwork = networkConfig.flatMap((network) => network)
+		.filter((ntwk) => ntwk.chainID.startsWith(networkID)).find(Boolean);
+
+	return matchingNetwork ? matchingNetwork.name : null;
+};
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/knownAccounts.js:42]: Alternative way of writing.

```suggestion
const networkConfig = Object.values(config.networks).flat();
const staticUrl = config.endpoints.liskStatic;

let knowledge = {};

const getAccountKnowledge = (address) => return knowledge[address] ? knowledge[address] : {};

const resolveNetworkByChainID = (chainID) => {
	const networkID = chainID.substring(0, LENGTH_NETWORK_ID);

	const matchingNetwork = networkConfig.find((network) => network.chainID.startsWith(networkID));

	return matchingNetwork ? matchingNetwork.name : null;
};
```

File: services/blockchain-indexer/shared/dataService/knownAccounts.js [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+
+const reloadAccountKnowledge = async () => {
+	logger.debug('Reloading known accounts...');
+
+	try {
+		const { data: { chainID } } = await getNetworkStatus();
+		const networkName = resolveNetworkByChainID(chainID);
+
+		if (networkName) {
+			const res = await HTTP.request(`${staticUrl}/known_${networkName}.json`);
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/knownAccounts.js:52]: Would it be better to use the framework helper api instead?

https://github.com/LiskHQ/lisk-service/blob/9830625a9a25269b704ec474a7a8434334b29bec/framework/src/http.js#L108

File: services/blockchain-indexer/tests/unit/shared/dataservice/knownAccounts.test.js [hunk 5]
```diff
@@ -0,0 +1,307 @@
...
+								owner: 'LiskHQ',
+								description: 'Initial seed',
+							},
+							address2: {
+								owner: 'Genesis',
+								description: 'Initial seed',
+							},
+						},
+						status: 200,
+					})),
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/tests/unit/shared/dataservice/knownAccounts.test.js:57]: Would it be more readable to move the response data to a helper constant file?
```suggestion
					request: jest.fn(() => Promise.resolve(mockedValidKnowledge)),
```

File: services/blockchain-indexer/tests/unit/shared/dataservice/knownAccounts.test.js [hunk 6]
```diff
@@ -0,0 +1,307 @@
...
+					info: async (data) => expect(data).toEqual('Updated known accounts cache with 2 entries.'),
+					warn: jest.fn(),
+					error: jest.fn(),
+				}),
+			};
+		});
+
+		// Mock getNetworkStatus function to resolve valid chainID
+		const { getNetworkStatus } = require('../../../../shared/dataService/business/network');
+		jest.mock('../../../../shared/dataService/business/network');
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/tests/unit/shared/dataservice/knownAccounts.test.js:70]: would it be more readable to use variables on top to point to this files? this way it would be easier to update in future if file path changes. Please consider the same for other occurrences.

File: services/blockchain-indexer/tests/unit/shared/dataservice/knownAccounts.test.js [hunk 7]
```diff
@@ -0,0 +1,307 @@
...
+								owner: 'LiskHQ',
+								description: 'Initial seed',
+							},
+							address2: {
+								owner: 'Genesis',
+								description: 'Initial seed',
+							},
+						},
+						status: 200,
+					})),
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/tests/unit/shared/dataservice/knownAccounts.test.js:268]:
```suggestion
					request: jest.fn(() => Promise.resolve(mockedValidKnowledge)),
```

File: services/blockchain-indexer/tests/unit/shared/dataservice/knownAccounts.test.js (hunk 6 above)
Comment (vardan10) [reply services/blockchain-indexer/tests/unit/shared/dataservice/knownAccounts.test.js:70]: It cant be imported on top since it needs to be imported only after mocking `lisk-service-framework` [here](https://github.com/LiskHQ/lisk-service/blob/3e9dcaf19df57821a73c3bfe492b8cf1d3a5319a/services/blockchain-indexer/tests/unit/shared/dataservice/knownAccounts.test.js#L40). And for every testcase mocking of `lisk-service-framework` is different.

**Review by sameersubudhi — APPROVED** [review]
