### PR TITLE
Fix inconsistencies with blockchain apps APIs

### LINKED ISSUE #1825: Fix inconsistencies with blockchain apps APIs
### Actual behavior
1. /blockchain/apps/meta/list
    a. Offset not working properly: Total entries are 4 but if offet=3 then response is empty
        http://devnet-service.liskdev.net:9901/api/v3/blockchain/apps/meta/list?offset=3
    b. Limit not working properly: Total entries are 4 but if Limit=1 then response is empty
        http://devnet-service.liskdev.net:9901/api/v3/blockchain/apps/meta/list?limit=1
    c. Sort dosent work
    d. Chain name works in case insensitive manner - not mentioned in swagger and documentation
        http://devnet-service.liskdev.net:9901/api/v3/blockchain/apps/meta/list?chainName=Colecti

2. /blockchain/apps/meta
    a. Chain name and display name works in case insensitive manner - not mentioned in swagger and documentation
        http://devnet-service.liskdev.net:9901/api/v3/blockchain/apps/meta?chainName=Lisk_MAINCHAIN
        http://devnet-service.liskdev.net:9901/api/v3/blockchain/apps/meta?displayName=LISK
    b. Sort dosent work

3. /blockchain/apps/meta/tokens/supported
    a. Sort dosent work

4. /blockchain/apps/meta/tokens/
    a. Chain name and token name works in case insensitive manner - not mentioned in swagger and documentation
        http://devnet-service.liskdev.net:9901/api/v3/blockchain/apps/meta/tokens?chainName=COLECTI
        http://devnet-service.liskdev.net:9901/api/v3/blockchain/apps/meta/tokens?tokenName=col

5. /blockchain/apps
    a. Chain name works in case insensitive manner - not mentioned in swagger and documentation 
        http://devnet-service.liskdev.net:9901/api/v3/blockchain/apps?chainName=ENEVTI

### Expected behavior
Above mentioned inconsistencies should not exist

### Steps to reproduce
Try the above endpoints on devnet

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Service v0.7.0-beta.4

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1825 #1826 

### How was it solved?
- [x] /blockchain/apps/meta/list
  - [x] a. Offset not working properly: Total entries are 4 but if offet=3 then response is empty
  - [x] b. Limit not working properly: Total entries are 4 but if Limit=1 then response is empty
  - [x] c. Sort dosent work
  - [x] d. Chain name works in case insensitive manner - not mentioned in swagger and documentation

- [x] /blockchain/apps/meta
  - [x] a. Chain name and display name works in case insensitive manner - not mentioned in swagger and documentation
  - [x] b. Sort dosent work

- [x] /blockchain/apps/meta/tokens/supported
  - [x] a. Sort dosent work
 
- [x] /blockchain/apps/meta/tokens/
  - [x] a. Chain name and token name works in case insensitive manner - not mentioned in swagger and documentation
 
- [x] /blockchain/apps
  - [x] a. Chain name works in case insensitive manner - not mentioned in swagger and documentation
 
- [x] GET pos/constants
  - [x] a. All SDK constants are not exposed by service
  - [x] b.punishmentWindow is not returned by service anymore
  - [x] c. Terminology for numberStandbyDelegates is changed to numberStandbyValidators.

- [x] GET pos/rewards/locked
  - [x] a. Returns empty meta object when queried with unknown name

- [x] GET pos/unlocks
  - [x] a. Returns error when queried with an unknown name:

- [x] GET pos/validators
  - [x] a. Returns empty response when called with same validators address and publicKey:

- [x] GET pos/rewards/claimable
  - [x] a. Returns empty meta object when queried with unknown name

### How was it tested?
Local

### CODE REVIEW

File: services/blockchain-app-registry/shared/metadata.js [hunk 1]
```diff
@@ -352,31 +354,27 @@ const resolveTokenMetaInfo = async (tokenInfoFromDB) => {
...
-		tokenInfoFromDB,
-		async (entry) => {
-			const chainID = entry.tokenID.substring(0, LENGTH_CHAIN_ID);
+	// eslint-disable-next-line no-restricted-syntax
+	for (const entry of tokenInfoFromDB) {
+		const chainID = entry.tokenID.substring(0, LENGTH_CHAIN_ID);
 
-			// Avoid reading same token metadata file multiple times
-			if (processedChainIDs.has(chainID)) return;
+		if (!processedChainIDs.has(chainID)) {
```
Comment (priojeetpriyom) [inline services/blockchain-app-registry/shared/metadata.js:363]: As it is a long code block would it be more readable if we use `continue` instead of indentation? Also, would it help others to understand if we keep the comment explaining why we are skipping the indexing for this particular token?

File: services/blockchain-app-registry/shared/metadata.js [hunk 2]
```diff
@@ -352,31 +354,27 @@ const resolveTokenMetaInfo = async (tokenInfoFromDB) => {
...
 			processedChainIDs.add(chainID);
 
+			// eslint-disable-next-line no-await-in-loop
```
Comment (priojeetpriyom) [inline services/blockchain-app-registry/shared/metadata.js:366]: would it be more readable to disable `no-await-in-loop` for the parent for loop code block?

File: services/blockchain-indexer/shared/dataService/pos/validators.js [hunk 3]
```diff
@@ -181,7 +181,7 @@ const getPosValidators = async params => {
 		const address = getLisk32AddressFromPublicKey(params.publicKey);
 
 		// Return empty response if user specified address and publicKey pair does not match
-		if (params.address && params.address.split(',').includes(address)) {
+		if (params.address && !params.address.split(',').includes(address)) {
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/pos/validators.js:184]: should we also initialize meta values to 0 for this api?

File: services/blockchain-app-registry/shared/metadata.js [hunk 4]
```diff
@@ -77,24 +77,32 @@ const getBlockchainAppsMetaList = async (params) => {
 		}];
 	}
 
-	const limit = params.limit * config.supportedNetworks.length;
+	let { offset } = params;
+	let { limit } = params;
```
Comment (nagdahimanshu) [inline services/blockchain-app-registry/shared/metadata.js:81]:
```suggestion
	let { offset, limit } = params;
```

File: services/blockchain-app-registry/shared/metadata.js [hunk 5]
```diff
@@ -77,24 +77,32 @@ const getBlockchainAppsMetaList = async (params) => {
...
 
-	if (defaultApps.length < params.limit) {
+	if (defaultApps.length < limit) {
+		// Update offset and limit
+		limit -= defaultApps.length;
+		offset -= await applicationMetadataTable.count(
+			{ ...params, isDefault: true },
+		);
+
+		if (offset < 0) offset = 0;
```
Comment (priojeetpriyom) [inline services/blockchain-app-registry/shared/metadata.js:94]: Would it be more appropiate to substract total number of default apps from the offset? suggesting just an alternative way of writing.

```suggestion
		const totalDefaultAppsCount = await applicationMetadataTable.count(
			{ isDefault: true },
		);

		offset = Math.max(totalDefaultAppsCount, 0);
```

**Review by priojeetpriyom — APPROVED** [review]

**Review by nagdahimanshu — APPROVED** [review]
LGTM 👍
