### PR TITLE
Vote endpoints without a param causes wrong HTTP response - Closes #233

### LINKED ISSUE #233: Vote endpoints without a param causes wrong HTTP response
### Actual behavior

The `/votes_sent` and `/votes_received` endpoints return error HTTP 500 instead of 4xx when there are no params defined.

### Expected behavior

The `/votes_sent` and `/votes_received` endpoints return error HTTP 400 when the when there are no params defined.

### Steps to reproduce

Call `/votes_sent` without a param.

### Which version(s) does this affect? (Environment, OS, etc...)

`0.2.0-beta.1`

### PR DESCRIPTION
**Pull request by sameersubudhi**
### What was the problem?
This PR resolves #233 

### How was it solved?
- [x] Add validation for required param from a pool of optional request parameters
- [x] Add validation to check if complementary parameters exist for a user-specified request param
- [x] Add corresponding integration test cases

### How was it tested?
Local + Jenkins

### CODE REVIEW

File: services/gateway/apis/http-version1/methods/votesSent.js [hunk 1]
```diff
@@ -30,6 +30,7 @@ module.exports = {
 		secpubkey: { optional: true, type: 'string', min: 64, max: 64 },
 		limit: { optional: true, min: 1, max: 100, type: 'number' },
 		offset: { optional: true, min: 0, type: 'number' },
+		onefrom: ['address', 'username', 'publickey', 'secpubkey'],
```
Comment (MichalTuleja) [inline services/gateway/apis/http-version1/methods/votesSent.js:33]: This can be defined separately at the upper level property. Ideally as array of arrays that define one of the properties that must be set.

Comment (sameersubudhi) [reply services/gateway/apis/http-version1/methods/votesSent.js]: Done!

**Review by nagdahimanshu — APPROVED** [review]
Looks good!

**Review by MichalTuleja — APPROVED** [review]
