### PR TITLE
Indexer crashes on validator endpoint call while indexing

### LINKED ISSUE #1687: Indexer crashes on validator endpoint call while indexing
### Actual behavior
Indexer crashes with following error if http://localhost:9901/api/v3/validator?address=lskaeec6426y8mkoq4oqgf5g4fsau738gb697pj8q endpoint is hit during indexing is going on.

```
{"error":true,"message":"Server error: Request is timed out when call 'indexer.validator' action on 'a31b745ba47f-1' node."}
```

### Expected behavior
Indexer should not crash and we should be able to get some response from the api.

### Steps to reproduce
 - Start lisk-core and keep running for a while. `rm -rf ~/.lisk && ./bin/run start --network devnet --api-ipc --api-ws --log info`
 - Execute stress test script in lisk core to generate transactions. `npm run test:stress`
 -  Start blockchain indexer and dependant services. Query above api while indexing is going on.

### Which version(s) does this affect? (Environment, OS, etc...)
- Lisk Service v0.7.0-beta.1

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1687 

### How was it solved?
- [x] Added exception handling
- [x] Added unit tests to indexer

### How was it tested?
- [x] Local

### CODE REVIEW

File: services/blockchain-indexer/shared/indexer/transactionProcessor/legacy/registerKeys.js
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/transactionProcessor/legacy/registerKeys.js:1]: Please remove the `try...catch` blocks from all the transaction processors (`applyTransaction` and `revertTransaction` hooks). We want the indexing jobs to fail incase the entire logic is not successfully executed. Upon failure, the job will retry to run the indexing later.

File: services/blockchain-indexer/shared/utils/account.js [hunk 1]
```diff
@@ -20,29 +20,35 @@ const {
...
 
+const logger = Logger();
+
 const MYSQL_ENDPOINT = config.endpoints.mysql;
 
 const getAccountsTable = () => getTableInstance(accountsTableSchema, MYSQL_ENDPOINT);
 
 const getLisk32AddressFromPublicKey = publicKey => getLisk32AddressFromPublicKeyHelper(Buffer.from(publicKey, 'hex'));
 
 const updateAccountPublicKey = async (publicKey) => {
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/utils/account.js:38]: Please remove the `try...catch` here too and as discussed offline, please create a new job queue that takes care of updating the account information. The job should automatically retry if the action fails.

File: services/blockchain-indexer/tests/unit/shared/utils/account.test.js [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+					},
+				};
+			});
+
+			const { updateAccountPublicKey } = require(acccountFilePath);
+
+			await updateAccountPublicKey(mockedPublicKey);
+		});
+
+		it('should log error when adding entry to database fails fails', async () => {
```
Comment (sameersubudhi) [inline services/blockchain-indexer/tests/unit/shared/utils/account.test.js:90]:
```suggestion
		it('should log error when adding entry to database fails', async () => {
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js [hunk 3]
```diff
@@ -20,31 +20,36 @@ const {
...
 
+	const accountsTable = await getAccountsTable();
+	// Update the account balance
+	const account = { address: tx.recipientAddress };
+	logger.trace(`Updating account index for the account with address ${account.address}.`);
+	await accountsTable.upsert(account, dbTrx);
+	logger.debug(`Updated account index for the account with address ${account.address}.`);
+
+	if (tx.executionStatus !== TRANSACTION_STATUS.SUCCESS) return;
+
```
Comment (vardan10) [inline services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js:52]: Did this changes because `indexAccountByAddress` function is not working. Should we remove it?

Same for other functions.

File: services/blockchain-indexer/config.js [hunk 4]
```diff
@@ -178,6 +178,10 @@ config.job = {
 		interval: process.env.JOB_INTERVAL_DELETE_FINALIZED_CCU_METADATA || 0,
 		schedule: process.env.JOB_SCHEDULE_DELETE_FINALIZED_CCU_METADATA || '0 2 * * *',
 	},
+	triggerAccountUpdates: {
+		interval: process.env.TRIGGER_ACCOUNT_UPDATES_INTERVAL || 0,
+		schedule: process.env.TRIGGER_ACCOUNT_UPDATES_SCHEDULE || '*/15 * * * *',
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/config.js:183]:
```suggestion
		interval: process.env.JOB_INTERVAL_TRIGGER_ACCOUNT_UPDATES || 0,
		schedule: process.env.JOB_SCHEDULE_TRIGGER_ACCOUNT_UPDATES || '*/15 * * * *',
```

File: services/blockchain-indexer/shared/indexer/accountIndex.js [hunk 5]
```diff
@@ -39,10 +47,17 @@ const getAccountsTable = () => getTableInstance(accountsTableSchema, MYSQL_ENDPO
...
+		const account = {
+			address: getLisk32AddressFromPublicKeyHelper(Buffer.from(publicKey, 'hex')),
+			publicKey,
+		};
+
 		const accountsTable = await getAccountsTable();
 		await accountsTable.upsert(account);
+	} catch (err) {
+		logger.warn('Failed to update accounts table. Will Retry.');
+		redis.sadd('pendingAccountsByPublicKey', publicKey);
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/accountIndex.js:60]: Can we please use constants for the queue names?
```suggestion
		await redis.sadd('pendingAccountsByPublicKey', publicKey);
```

File: services/blockchain-indexer/shared/utils/account.js [hunk 6]
```diff
@@ -33,16 +34,11 @@ const getAccountsTable = () => getTableInstance(accountsTableSchema, MYSQL_ENDPO
...
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/utils/account.js:36]: This could be a one-liner.
```suggestion
const updateAccountPublicKey = async (publicKey) => indexAccountByPublicKey(publicKey);
```

File: services/blockchain-indexer/shared/utils/account.js [hunk 7]
```diff
@@ -33,16 +34,11 @@ const getAccountsTable = () => getTableInstance(accountsTableSchema, MYSQL_ENDPO
...
-	const accountsTable = await getAccountsTable();
-	await accountsTable.upsert({
-		address: getLisk32AddressFromPublicKey(publicKey),
-		publicKey,
-	});
+	indexAccountByPublicKey(publicKey);
 };
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/utils/account.js:38]:
```suggestion
```

File: services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js (hunk 3 above)
Comment (sameersubudhi) [reply services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js:52]: As discussed offline, please update the implementation for `indexAccountByAddress` and others. Please revert the transaction processor changes.

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/blockchain-indexer/jobs/indexer/updateAccounts.js [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+ */
+const logger = require('lisk-service-framework').Logger();
+
+const config = require('../../config');
+const { triggerAccountUpdates } = require('../../shared/indexer/accountIndex');
+
+module.exports = [
+	{
+		name: 'trigger.accountUpdates',
+		description: 'Triggers account updates',
```
Comment (sameersubudhi) [inline services/blockchain-indexer/jobs/indexer/updateAccounts.js:24]:
```suggestion
		name: 'trigger.account.updates',
		description: 'Triggers the queued account updates.',
```

File: services/blockchain-indexer/shared/dataService/business/pendingTransactions.js [hunk 9]
```diff
@@ -61,7 +59,7 @@ const getPendingTransactionsFromCore = async () => {
 				};
 			}
 
-			updateAccountPublicKey(normalizedTransaction.senderPublicKey);
+			indexAccountByPublicKey(normalizedTransaction.senderPublicKey);
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/dataService/business/pendingTransactions.js:62]: Since this queue ultimately only indexes the publicKey and address, renaming the method to `updateAccountPublicKey` or `indexAccountPublicKey` would make more sense.

File: services/blockchain-indexer/shared/indexer/accountIndex.js [hunk 10]
```diff
@@ -76,50 +80,41 @@ const accountAddrUpdateQueue = Queue(
 	updateAccountInfoAddr,
 	config.queue.accountQueueByAddress.concurrency,
 );
-const accountDirectUpdateQueue = Queue(
-	config.endpoints.cache,
-	config.queue.accountQueueDirect.name,
-	updateAccountWithData,
-	config.queue.accountQueueDirect.concurrency,
+const indexAccountByPublicKey = async (publicKey) => redis.sadd(
+	config.queue.indexAccountByPublicKey.name,
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/accountIndex.js:84]:
```suggestion
const indexAccountPublicKey = async (publicKey) => redis.sadd(
	config.queue.indexAccountPublicKey.name,
```

File: services/blockchain-indexer/shared/indexer/accountIndex.js [hunk 11]
```diff
@@ -76,50 +80,41 @@ const accountAddrUpdateQueue = Queue(
...
+	publicKey,
 );
 
-const indexAccountByPublicKey = async (publicKey) => redis.sadd('pendingAccountsByPublicKey', publicKey);
-
-const indexAccountByAddress = async (address) => redis.sadd('pendingAccountsByAddress', address);
+const indexAccountByAddress = async (address) => redis.sadd(
+	config.queue.indexAccountByAddress.name,
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/accountIndex.js:89]:
```suggestion
const indexAccountAddress = async (address) => redis.sadd(
	config.queue.indexAccountAddress.name,
```

File: services/blockchain-indexer/shared/indexer/accountIndex.js [hunk 12]
```diff
@@ -76,50 +80,41 @@ const accountAddrUpdateQueue = Queue(
...
+	address,
+);
 
 const triggerAccountUpdates = async () => {
-	const publicKeys = await redis.spop('pendingAccountsByPublicKey', 64);
+	const publicKeys = 	await redis.spop(
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/accountIndex.js:94]:
```suggestion
	const publicKeys = await redis.spop(
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]
Looks good overall but needs the following minor changes.

**Review by nagdahimanshu — APPROVED** [review]
LGTM 👍

File: services/blockchain-indexer/config.js [hunk 13]
```diff
@@ -99,6 +99,14 @@ config.queue = {
 		name: 'IndexBlocksQueue',
 		concurrency: 1,
 	},
+	indexAccountPublicKey: {
+		name: 'pendingAccountsByPublicKey',
+		concurrency: 64,
+	},
+	indexAccountAddress: {
+		name: 'pendingAccountsByAddress',
```
Comment (sameersubudhi) [inline services/blockchain-indexer/config.js:107]:
```suggestion
		name: 'pendingAccountPublicKeyUpdates',
		concurrency: 64,
	},
	indexAccountAddress: {
		name: 'pendingAccountAddressUpdates',
```

**Review by sameersubudhi — APPROVED** [review]
LGTM 👍
