### PR TITLE
Events are fetched using block height instead of block id for deleted block events

### LINKED ISSUE #1697: HTTP rate limiter trusts X-Forwarded-For header from the client
### Actual behavior
When a deleted block is indexed, events are fetched using block height instead of block ID
https://github.com/LiskHQ/lisk-service/blob/development/services/blockchain-indexer/shared/indexer/blockchainIndex.js#L272

We need to fetch events using block ID as the blockchain might have forked a new block at the same height.

### Expected behavior
Events must be fetched using block ID.

### Steps to reproduce
Need to update logic here:
https://github.com/LiskHQ/lisk-service/blob/development/services/blockchain-indexer/shared/indexer/blockchainIndex.js#L272

### Additional information
Please verify event fetching information in other places as well.

### Which version(s) does this affect? (Environment, OS, etc...)
release/0.7.0

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1697 

### How was it solved?
- [x] Added blockID to events table
- [x] Added caching of events using block ID
- [x] Updated deleted block handling to fetch events by blockID

### How was it tested?
- [x] Local

### CODE REVIEW

File: services/blockchain-indexer/shared/dataService/business/events.js [hunk 1]
```diff
@@ -70,6 +71,31 @@ const getEventsByHeight = async (height) => {
 	return eventsFromNode;
 };
 
+const getEventsByBlockID = async (blockID) => {
+	// Get from cache
+	const cachedEvents = await eventCacheByBlockID.get(blockID);
+	if (cachedEvents) return JSON.parse(cachedEvents);
+
+	// Get from DB only when isPersistEvents is enabled
+	if (config.isPersistEvents) {
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/dataService/business/events.js:80]: The `if` condition can be removed. We also maintain the events for non-finalized blocks even if `config.isPersistEvents` is not set.

File: services/blockchain-indexer/shared/dataService/business/events.js [hunk 2]
```diff
@@ -70,6 +71,31 @@ const getEventsByHeight = async (height) => {
...
+		const eventsTable = await getEventsTable();
+		const dbEventStrs = await eventsTable.find({ blockID }, ['eventStr']);
+
+		if (dbEventStrs.length) {
+			const dbEvents = dbEventStrs
+				.map(({ eventStr }) => eventStr ? JSON.parse(eventStr) : eventStr);
+			await eventCacheByBlockID.set(blockID, JSON.stringify(dbEvents));
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/dataService/business/events.js:87]: Caching of the data can be done asynchronously without delaying the response.
```suggestion
			eventCacheByBlockID.set(blockID, JSON.stringify(dbEvents));
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/blockchain-indexer/tests/unit/shared/dataservice/business/events.test.js [hunk 3]
```diff
@@ -0,0 +1,167 @@
...
+ * LICENSE file.
+ *
+ * Removal or modification of this copyright notice is prohibited.
+ *
+ */
+/* eslint-disable import/no-dynamic-require */
+const path = require('path');
+
+const mockedBlockID = '89a9f8dd0e9d15e54268f952b2e9430e799968169376273f715480d058a67dc4';
+const mockedEvents = [{ id: 'c3a1f388859d69105241473ce9a49d831c8eb0043f717a626b2901f52ed3610c', name: 'transfer' }, { id: 'c3c120616d202a36e659248e6d384bbbf3429d4d56a6066f368aa14d16e81dfb', name: 'validatorRegistered' }];
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/tests/unit/shared/dataservice/business/events.test.js:20]: Instead of defining separate constant for the events here, may be we can directly use the event already defined under `tests/constants` directory. 
Ref: https://github.com/LiskHQ/lisk-service/blob/release/0.7.0/services/blockchain-indexer/tests/constants/events.js#L29

File: services/blockchain-indexer/tests/unit/shared/dataservice/business/events.test.js [hunk 4]
```diff
@@ -0,0 +1,167 @@
...
+				},
+			};
+		});
+
+		const { getEventsByBlockID } = require(mockEventsFilePath);
+		const events = await getEventsByBlockID(mockedBlockID);
+		expect(events).toEqual(mockedEvents);
+	});
+
+	it('should return events from DB and if cache miss', async () => {
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/tests/unit/shared/dataservice/business/events.test.js:53]:
```suggestion
	it('should return events from DB if not available in cache', async () => {
```

File: services/blockchain-indexer/tests/unit/shared/dataservice/business/events.test.js [hunk 5]
```diff
@@ -0,0 +1,167 @@
...
+					getTableInstance: jest.fn(),
+				},
+			};
+		});
+
+		const { cacheEventsByBlockID } = require(mockEventsFilePath);
+		await cacheEventsByBlockID(mockedBlockID, mockedEvents);
+	});
+
+	it('Show throw error if cache throws error', async () => {
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/tests/unit/shared/dataservice/business/events.test.js:147]:
```suggestion
	it('should throw error if cache throws error', async () => {
```

**Review by sameersubudhi — APPROVED** [review]
LGTM 👍

File: services/gateway/config.js [hunk 6]
```diff
@@ -46,6 +46,8 @@ config.rateLimit.enable = Boolean(String(process.env.HTTP_RATE_LIMIT_ENABLE).toL
 config.rateLimit.window = Number(process.env.HTTP_RATE_LIMIT_WINDOW) || 10; // in seconds
 // Max number of requests during window
 config.rateLimit.connectionLimit = Number(process.env.HTTP_RATE_LIMIT_CONNECTIONS || 200);
+config.rateLimit.enableXForwardedFor = Boolean(String(process.env.HTTP_RATE_LIMIT_ENABLE_X_FORWARDED_FOR).toLowerCase() === 'true');
+config.rateLimit.reverseProxyCount = Number(process.env.HTTP_RATE_LIMIT_REVERSE_PROXY_COUNT || 0);
```
Comment (sameersubudhi) [inline services/gateway/config.js:50]: Could you also please update the `docker/example.env`, `ecosystem.config.json` and the gateway README with these environment variables?
```suggestion
config.rateLimit.enableXForwardedFor = Boolean(String(process.env.HTTP_RATE_LIMIT_ENABLE_X_FORWARDED_FOR).toLowerCase() === 'true');
config.rateLimit.numKnownProxies = Number(process.env.HTTP_RATE_LIMIT_NUM_KNOWN_PROXIES || 0);
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/gateway/README.md [hunk 7]
```diff
@@ -35,6 +35,8 @@ A list of the most commonly used environment variables is presented below:
 - `HTTP_RATE_LIMIT_ENABLE`: Boolean flag to enable HTTP rate limiter. Disabled by default. To enable, set it to `true`.
 - `HTTP_RATE_LIMIT_WINDOW`: To keep a record of requests in the memory (in seconds). By default, it is set to 10 seconds.
 - `HTTP_RATE_LIMIT_CONNECTIONS`: Maximum number of allowed requests for a specified window, configured by `HTTP_RATE_LIMIT_WINDOW`.
+- `HTTP_RATE_LIMIT_ENABLE_X_FORWARDED_FOR`: When set to true, the rate limiting algorithm considers the X-Forwarded-For header value to determine the client's IP address for rate limiting purposes. By default, it is set to `false`.
+- `HTTP_RATE_LIMIT_NUM_KNOWN_PROXIES`: Defines the number of proxies that exist between the gateway and the external client application, enabling accurate identification of the client's IP address for rate limiting. By default, it is set to 0.
```
Comment (sameersubudhi) [inline services/gateway/README.md:39]:
```suggestion
- `HTTP_RATE_LIMIT_NUM_KNOWN_PROXIES`: Defines the number of proxies that exist between the gateway and the external client application, enabling accurate identification of the client's IP address for rate limiting. Requires `HTTP_RATE_LIMIT_ENABLE_X_FORWARDED_FOR` to be enabled. By default, it is set to 0.
```

**Review by nagdahimanshu — APPROVED** [review]
LGTM 👍
