### PR TITLE
Missing validation for estimate-fees API

### LINKED ISSUE #1824: Missing validation for estimate-fees API
### Actual behavior
API timeout when supplied with incorrect token ID for cross chain transfers.
```
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/transactions/estimate-fees' \
--header 'Content-Type: application/json' \
--data '{"transaction":{"module":"token","command":"transferCrossChain","nonce":"4","fee":"0","senderPublicKey":"3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c","params":{"tokenID":"0400000000000001","amount":"1000000000","recipientAddress":"lskbgyrx3v76jxowgkgthu9yaf3dr29wqxbtxz8yp","data":"","receivingChainID":"04000001"}}}'
```

2.  API Timeout if recipient address is new and not initailized
```
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/transactions/estimate-fees' \
--header 'Content-Type: application/json' \
--data '{"transaction":{"module":"token","command":"transferCrossChain","nonce":"4","fee":"0","senderPublicKey":"3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c","params":{"tokenID":"0400000000000000","amount":"1000000000","recipientAddress":"lskbgyrx3v76jxowgkgthu9yaf3dr29wqxbtxz8yy","data":"","receivingChainID":"04000001"}}}'
```

3. Does not validate params for pos validator transactions. Pass a invalid proof of possession, blsKey or generator address. Should we do a regex check as its done for transfer commands?
```
curl --location 'http://devnet-service.liskdev.net:9901/api/v3/transactions/estimate-fees' \
--header 'Content-Type: application/json' \
--data '{"transaction": {
        "module": "pos",
        "command": "registerValidator",
        "fee": "100000000",
        "nonce": "1",
        "senderPublicKey": "3972849f2ab66376a68671c10a00e8b8b67d880434cc65b04c6ed886dfa91c2c",
        "signatures": [
            "c7fd1abf9a552fa9c91b4121c87ae2c97cb0fc0aecc87d0ee8b1aa742238eef4a6815ddba31e21144c9652a7bd5c05577ae1100eac34fba43da6fc4879b8f206"
        ],
        "params": {
            "name": "test_validator",
            "blsKey": "a984c12c76b42b2d6ef2cae7ce09951e7d71eb160abdedbfba51bd216c42f2f3eda04a2e57b2cfb01768b94419b65190",
            "proofOfPossession": "ab7661489a290464310c8615b387117ff27a209742e0e711f22d5ba3e7480de4eda293a651a48be9ae57b569a977d65e101179e1fcd73ab32c6c3fef4a1aedc7119e90eb2af7a3450399b15743c145bb49fdcb61b333817345c1d46769005d04",
            "generatorKey": "b9c0211c8eb94ee61154a4dc7af36d2a36e14dd1644b43aa250186bfa107ce6b"
        },
        "id": "d96c777b67576ddf4cd933a97a60b4311881e68e3c8bef1393ac0020ec8a506c",
        "size": 167,
        "minFee": "166000"}}'
```

### Expected behavior
Above API responses should throw proper error and not timeout.

### Steps to reproduce
Try the above endpoints on devnet

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Service v0.7.0-beta.4

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1824 

### How was it solved?
- [x] Added regex validations to tx params in estimate fees API
- API timeout when supplied with incorrect token ID for cross chain transfers. (Fixed by https://github.com/LiskHQ/lisk-service/pull/1818)
- API Timeout if recipient address is new and not initailized (Fixed by https://github.com/LiskHQ/lisk-service/pull/1818)

### How was it tested?
Local

### CODE REVIEW

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 1]
```diff
@@ -244,16 +244,17 @@ const calcAdditionalFees = async (transaction) => {
...
+const validateTransactionParams = params => {
+	const {
+		tokenID,
+		recipientAddress,
+		receivingChainID,
+		sendingChainID,
+		messageFeeTokenID,
+		blsKey,
+		proofOfPossession,
+		generatorKey } = params.transaction.params;
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:256]:
```suggestion
	const {
		tokenID,
		recipientAddress,
		receivingChainID,
		sendingChainID,
		messageFeeTokenID,
		blsKey,
		proofOfPossession,
		generatorKey,
	} = params.transaction.params;
```

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 2]
```diff
@@ -262,6 +263,41 @@ const estimateTransactionFees = async params => {
...
+	if (proofOfPossession && !regex.PROOF_OF_POSSESSION.test(proofOfPossession)) {
+		throw new ValidationException('Incorrect \'proofOfPossession\' specified in transaction params.');
+	}
+
+	if (generatorKey && !regex.PUBLIC_KEY.test(generatorKey)) {
+		throw new ValidationException('Incorrect \'generatorKey\' specified in transaction params.');
+	}
+
+	if (receivingChainID && !regex.CHAIN_ID.test(receivingChainID)) {
+		throw new ValidationException('Incorrect \'chainID\' specified in transaction params.');
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:279]:
```suggestion
		throw new ValidationException('Incorrect \'receivingChainID\' specified in transaction params.');
```

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 3]
```diff
@@ -262,6 +264,41 @@ const estimateTransactionFees = async params => {
...
+		throw new ValidationException('Incorrect \'receivingChainID\' specified in transaction params.');
+	}
+
+	if (sendingChainID && !regex.CHAIN_ID.test(sendingChainID)) {
+		throw new ValidationException('Incorrect \'sendingChainID\' specified in transaction params.');
+	}
+
+	if (messageFeeTokenID && !regex.TOKEN_ID.test(messageFeeTokenID)) {
+		throw new ValidationException('Incorrect \'messageFeeTokenID\' specified in transaction params.');
+	}
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:289]: Would it have better code if we integrate the checks in [gateway file ](https://github.com/LiskHQ/lisk-service/blob/51b074adc43117d70d514fc622f4ce7b8d09c402/services/blockchain-connector/methods/encoder.js#L26-L36)and indexer methods [file](https://github.com/LiskHQ/lisk-service/blob/6d8b0c44a81777401d38a84d3719927402bcab68/services/blockchain-indexer/methods/dataService/transactions.js#L79C36-L79C50) instead? we won't need the `validateTransactionParams` function in that case.

[Example](https://github.com/LiskHQ/lisk-service/blob/51b074adc43117d70d514fc622f4ce7b8d09c402/services/blockchain-connector/methods/encoder.js#L26-L36)

```suggestion
```

Comment (vardan10) [reply services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js]: Updated the code to use `validator.validate` to validate all tx params instead.

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 4]
```diff
@@ -244,6 +246,36 @@ const calcAdditionalFees = async (transaction) => {
...
 
+const getTransactionParamsSchema = (transaction, metadata) => {
+	const moduleMetadata = metadata.modules.find(m => m.name === transaction.module);
+	const { params: schema } = moduleMetadata.commands.find(c => c.name === transaction.command);
+	return schema;
+};
+
+const validateTransactionParams = async transaction => {
+	// Mock optional values if not present before schema validation.
+	if (transaction.module === MODULE.INTEROPERABILITY
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:257]: This should be token module
```suggestion
	if (transaction.module === MODULE.TOKEN
```

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 5]
```diff
@@ -244,6 +246,36 @@ const calcAdditionalFees = async (transaction) => {
...
+			transaction.params.messageFee = '10000000';
+		}
+
+		if (!('messageFeeTokenID' in transaction.params)) {
+			transaction.params.messageFeeTokenID = '0000000000000000';
+		}
+	}
+
+	const metadata = await getSystemMetadata();
+	const txParamsSchema = getTransactionParamsSchema(transaction, metadata);
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:269]: Instead of calling system metadata, we can call `getSchemas` method from `services/blockchain-indexer/shared/dataService/business/schemas.js`. In that case we can just do something like:
```
const allSchemas = await getSchemas();
const {txParamsSchema: schema} = allSchemas.data.commands.find(e => e. moduleCommand === `${transaction.module}:${transaction.command}`);
```

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 6]
```diff
@@ -244,6 +246,36 @@ const calcAdditionalFees = async (transaction) => {
...
+	const parsedTxParams = parseInputBySchema(transaction.params, txParamsSchema);
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:270]: I am not sure but i think we don't need to parse params. we can directly pass it to validator.

**Review by nagdahimanshu — CHANGES_REQUESTED** [review]

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 7]
```diff
@@ -244,6 +246,30 @@ const calcAdditionalFees = async (transaction) => {
 	return additionalFees;
 };
 
+const validateTransactionParams = async transaction => {
+	// Mock optional values if not present before schema validation.
+	if (transaction.module === MODULE.TOKEN
+		&& transaction.command === COMMAND.TRANSFER_CROSS_CHAIN) {
+		if (!('messageFee' in transaction.params)) {
+			transaction.params.messageFee = '10000000';
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:254]: would it be better for code consistency to use constants instead of hardcoding the value?

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 8]
```diff
@@ -244,6 +246,30 @@ const calcAdditionalFees = async (transaction) => {
...
+		}
+
+		if (!('messageFeeTokenID' in transaction.params)) {
+			transaction.params.messageFeeTokenID = '0000000000000000';
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:258]: same question here regarding constant

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 9]
```diff
@@ -244,6 +246,30 @@ const calcAdditionalFees = async (transaction) => {
...
+		}
+	}
+
+	const allSchemas = await getSchemas();
+	const { schema: txParamsSchema } = allSchemas.data.commands.find(e => e.moduleCommand === `${transaction.module}:${transaction.command}`);
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:263]: will we get an error here if no schema value matches with the user supplied `transaction.module` and `transaction.command`?

File: services/blockchain-indexer/shared/utils/parser.js [hunk 10]
```diff
@@ -41,7 +41,9 @@ const parseInputBySchema = (input, schema) => {
 		if (schemaDataType === 'string') return String(input);
 		if (schemaDataType === 'boolean') return Boolean(input);
 		if (schemaDataType === 'bytes') {
-			if (schema.format === 'lisk32') { return getAddressFromLisk32Address(input); }
+			if (schema.format === 'lisk32') {
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/utils/parser.js:44]: same question regarding constant

**Review by priojeetpriyom — APPROVED** [review]

File: services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js [hunk 11]
```diff
@@ -244,6 +249,36 @@ const calcAdditionalFees = async (transaction) => {
...
+		if (!('messageFeeTokenID' in transaction.params)) {
+			transaction.params.messageFeeTokenID = DEFAULT_MESSAGE_FEE_TOKEN_ID;
+		}
+	}
+
+	const allSchemas = await getSchemas();
+	const txCommand = allSchemas.data.commands.find(e => e.moduleCommand === `${transaction.module}:${transaction.command}`);
+
+	if (!txCommand || !txCommand.schema) {
+		throw new InvalidParamsException(`${transaction.module}:${transaction.command} is not a valid transaction.`);
```
Comment (nagdahimanshu) [inline services/blockchain-indexer/shared/dataService/business/transactionsEstimateFees.js:269]: Shouldn't this be `ValidationException`?
