### PR TITLE
Lisk Service failing to reconnect to Lisk Core (intermittent) - Closes #1000

### LINKED ISSUE #1000: Lisk Service failing to reconnect to Lisk Core (intermittent)
### Actual behavior
Lisk Service will lose its connection to Lisk Core and then sometimes fail to reconnect
The RequestTimeoutError below will repeat until it's manually restarted
```
2022-03-11T12:13:54.322 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:55.940 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:55.961 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:56.240 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:56.360 WARN [BROKER] Service 'core.network.status' is not available.
2022-03-11T12:13:56.991 INFO [REGISTRY] Node 'core.my_host-1' reconnected.
2022-03-11T12:14:07.963 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
2022-03-11T12:14:07.965 ERROR [GATEWAY] <= 504 Request error: RequestTimeoutError: Request is timed out whe
n call 'core.network.status' action on 'core.my_host-1' node.
RequestTimeoutError: Request is timed out when call 'core.network.status' action on 'core.my_host-1' node.
    at /home/lisk/lisk-service/gateway/node_modules/moleculer/src/middlewares/timeout.js:42:14
    at async getStatus (/home/lisk/lisk-service/gateway/shared/status.js:36:24)
    at async Service.callAction (/home/lisk/lisk-service/gateway/shared/moleculer-web/methods.js:100:16)
    at async /home/lisk/lisk-service/gateway/node_modules/moleculer-web/src/index.js:443:22
Data:
Request params: {}
Request body: {}
2022-03-11T12:14:07.983 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
2022-03-11T12:14:07.984 ERROR [GATEWAY] <= 504 Request error: RequestTimeoutError: Request is timed out whe
n call 'core.network.status' action on 'core.my_host-1' node.
RequestTimeoutError: Request is timed out when call 'core.network.status' action on 'core.my_host-1' node.
    at /home/lisk/lisk-service/gateway/node_modules/moleculer/src/middlewares/timeout.js:42:14
    at async getStatus (/home/lisk/lisk-service/gateway/shared/status.js:36:24)
    at async Service.callAction (/home/lisk/lisk-service/gateway/shared/moleculer-web/methods.js:100:16)
    at async /home/lisk/lisk-service/gateway/node_modules/moleculer-web/src/index.js:443:22
Data:
Request params: {}
Request body: {}
2022-03-11T12:14:08.273 WARN [BROKER] Request 'core.network.status' is timed out.,[object Object]
```
### Expected behavior
It should eventually succeed in reconnecting
### Steps to reproduce
It's intermittent 
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.3, Linux, Docker

### PR DESCRIPTION
**Pull request by sameersubudhi**
### What was the problem?
This PR resolves #1000 

### How was it solved?
- [x] Reset the `isInstantiating` flag if the waiting is too long

### How was it tested?
Local (Restart Lisk Core node multiple times while Lisk Service keeps running)

### CODE REVIEW

File: services/core/shared/core/compat/common/wsRequest.js [hunk 1]
```diff
@@ -42,6 +44,11 @@ const instantiateClient = async () => {
 			}
 			return clientCache;
 		}
+
+		if ((Date.now() - instantiationBeginTime) > 500) {
```
Comment (MichalTuleja) [inline services/core/shared/core/compat/common/wsRequest.js:48]: Can you please give that `500` a name?
As previously discussed, did you consider a different value?

**Review by MichalTuleja — CHANGES_REQUESTED** [review]

File: services/core/shared/core/compat/common/wsRequest.js (hunk 1 above)
Comment (sameersubudhi) [reply services/core/shared/core/compat/common/wsRequest.js]: Done!
The client instantiation time varies between `9-20ms`. So, updated the wait time to be `50ms`.

**Review by MichalTuleja — APPROVED** [review]
LGTM 👍
