### PR TITLE
Fix transaction sorting by timestamp - Closes #285

### LINKED ISSUE #285: Fix transaction sorting by timestamp
### Actual behavior

Fix transaction sorting by timestamp does not work correctly.

### Expected behavior

Fix transaction sorting by timestamp works correctly.

### Steps to reproduce

Retrieve transactions sorted by timestamp.

### Which version(s) does this affect? (Environment, OS, etc...)

`0.2.0-beta.1` connected to a SDKv4 node.

### PR DESCRIPTION
**Pull request by sameersubudhi**
### What was the problem?
This PR resolves #285 

### How was it solved?

Main issue:
- [x] Build block index based on blocks with transactions
- [x] Build transaction index per block
- [x] Build transaction index per account

Minor issues:
- [x] Fix bug causing infinite `/node/constants` polling

### How was it tested?
Local

### CODE REVIEW

File: services/core/shared/core/compat/sdk_v4/blocks.js [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+		const topHeightFromBatch = (blocks.data.pop()).height;
+		// eslint-disable-next-line no-await-in-loop
+		await bIdCache.set('lastIndexedHeight', topHeightFromBatch);
+	}
+	logger.info(`Finished building block index (${from}-${to})`);
+};
+
+const init = async () => {
+	try {
+		currentHeight = (await coreApi.getNodeStatus()).data.height;
```
Comment (MichalTuleja) [inline services/core/shared/core/compat/sdk_v4/blocks.js:146]: Change to `getNetworkStatus`

**Review by nagdahimanshu — APPROVED** [review]
LGTM!

**Review by sameersubudhi — COMMENTED** [review]
The changes look good to me! 👍
