### PR TITLE
Minor API discrepancies - Closes #781

### LINKED ISSUE #781: Minor API discrepancies
### Actual behavior

- lastBlockHeight is number in fees.meta but string in network.status
- height is string but finalizedHeight is number within network.status.data

### Expected behavior

Make them returned as integers.

Refer to the docs: https://github.com/LiskHQ/lisk-service/blob/development/docs/api/version2.md#network-status

### Steps to reproduce

Call the network status endpoint.

### PR DESCRIPTION
**Pull request by sameersubudhi**
### What was the problem?
This PR resolves #781 

### How was it solved?
- [x] Update the API documentation
- [x] Fix casting datatypes at the Gateway
- [x] Separate integration test schema for `v2` API
- [x] Fix integration test schema for network status
- [x] Improve integration tests
- [x] Cherry-pick commit `85881a9f4a486f7fd7e6a546ca6a71d427392f36` (Separate docker volumes for separate MySQL instances)

### How was it tested?
Local

### CODE REVIEW

File: services/core/shared/core/compat/sdk_v5/network.js [hunk 1]
```diff
@@ -15,26 +15,53 @@
...
+	return location;
+};
+
+const calculateDefaultReward = (height, blockRewardArgs) => {
+	if (height < blockRewardArgs.offset) {
+		return BigInt(0);
+	}
+
+	return blockRewardArgs.milestones[calculateMilestone(height, blockRewardArgs)];
+};
```
Comment (nagdahimanshu) [inline services/core/shared/core/compat/sdk_v5/network.js:41]: This can be simplified like this (Optional):
```suggestion
const calculateDefaultReward = (height, blockRewardArgs) => (height < blockRewardArgs.offset)
	? BigInt(0)
	: blockRewardArgs.milestones[calculateMilestone(height, blockRewardArgs)];
```

**Review by nagdahimanshu — COMMENTED** [review]
looks good but we also need to update the swagger docs to reflect the change with `milestone` and `currentReward`. (https://github.com/LiskHQ/lisk-service/blob/781-minor-api-discrepancies/services/gateway/apis/http-version2/swagger/definitions/networkStatus.json)

File: services/core/shared/core/compat/sdk_v5/network.js (hunk 1 above)
Comment (sameersubudhi) [reply services/core/shared/core/compat/sdk_v5/network.js:41]: I'm not modifying them as these methods have been taken from the Lisk SDK repo.

**Review by nagdahimanshu — APPROVED** [review]
LGTM 👍

**Review by MichalTuleja — APPROVED** [review]
LGTM 👍
