### PR TITLE
Fix multisignature memberships - Closes #600

### LINKED ISSUE #600: Fix multisignature memberships in accounts endpoint
### Actual behavior

The multisignature memberships are not added to the account properties.

### Expected behavior

The memberships should be returned as specified in the #250.

### Steps to reproduce

Compare members from:
https://betanet5-service-staging.lisk.io/api/v2/accounts?address=lsk7522yopsetpqnoanrs7n57o98zcn9n8cbjt2ax

with memberships from:
https://betanet5-service-staging.lisk.io/api/v2/accounts?address=lskzuj4qpmndg5owqkt5rzhyexe2qm88nqjk3fz7v

### Which version(s) does this affect? (Environment, OS, etc...)

`v0.4.0-rc.0` and below

### PR DESCRIPTION
**Pull request by nagdahimanshu**
### What was the problem?
This PR resolves #600 

### How was it solved?
- [x] Add new schema for `multi-signature membership`
- [x] Index multi-signature membership info on every multisig transaction
- [x] Implement getMultiSignaturememberships methods to resolve memberships
- [x] Update gateway to pass memberships in the response as specified. 

### How was it tested?
Local + Jenkins

### CODE REVIEW

File: services/core/shared/core/compat/sdk_v5/accounts.js [hunk 1]
```diff
@@ -432,7 +434,51 @@ const getMultisignatureGroups = async account => {
...
+					address: result && result.address ? result.address : undefined,
+					username: result && result.username ? result.username : undefined,
+					publicKey: result && result.publicKey ? result.publicKey : undefined,
+				});
+			},
+			{ concurrency: memberInfo.length },
+		);
+	}
+	return multisignatureMemberships;
+};
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/accounts.js:458]: Please consider renaming it to `membershipInfo`, since the resolved info contains and focuses on all the memberships for the queried account address. And, since the `db.find()` always ensures the return of an array in the response, the check seems redundant.

```suggestion
const getMultisignatureMemberships = async account => {
	const multisignatureMemberships = {memberships: []};
	const multisignatureDB = await getMultisignatureIndex();
	const membershipInfo = await multisignatureDB.find({ memberAddress: account.address });

	await BluebirdPromise.map(
		membershipInfo,
		async membership => {
			const result = await getIndexedAccountInfo({ address: membership.groupAddress });
			multisignatureMemberships.memberships.push({
				address: result && result.address ? result.address : undefined,
				username: result && result.username ? result.username : undefined,
				publicKey: result && result.publicKey ? result.publicKey : undefined,
			});
		},
		{ concurrency: membershipInfo.length },
	);
	return multisignatureMemberships;
};
```

File: services/core/shared/core/compat/sdk_v5/accounts.js [hunk 2]
```diff
@@ -432,7 +434,51 @@ const getMultisignatureGroups = async account => {
...
+		const members = {
+			id: getBase32AddressFromPublicKey(tx.senderPublicKey)
+				.concat('_', getBase32AddressFromPublicKey(key)),
+			memberAddress: getBase32AddressFromPublicKey(key),
+			groupAddress: getBase32AddressFromPublicKey(tx.senderPublicKey),
+		};
+		multisignatureInfoToIndex.push(members);
+	});
+	return multisignatureInfoToIndex;
+};
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/accounts.js:481]: Please consider refactoring the code as below to avoid duplication of the logic.

```suggestion
const resolveMultisignatureMemberships = tx => {
	const multisignatureInfoToIndex = [];
	const allKeys = tx.asset.mandatoryKeys.concat(tx.asset.optionalKeys);
	allKeys.forEach(key => {
		const members = {
			id: getBase32AddressFromPublicKey(tx.senderPublicKey)
				.concat('_', getBase32AddressFromPublicKey(key)),
			memberAddress: getBase32AddressFromPublicKey(key),
			groupAddress: getBase32AddressFromPublicKey(tx.senderPublicKey),
		};
		multisignatureInfoToIndex.push(members);
	});
	return multisignatureInfoToIndex;
};
```
or 

```suggestion
const resolveMultisignatureMemberships = tx => {
	const multisignatureInfoToIndex = [];
	tx.asset.mandatoryKeys
		.concat(tx.asset.optionalKeys)
		.forEach(key => {
			const members = {
				id: getBase32AddressFromPublicKey(tx.senderPublicKey)
					.concat('_', getBase32AddressFromPublicKey(key)),
				memberAddress: getBase32AddressFromPublicKey(key),
				groupAddress: getBase32AddressFromPublicKey(tx.senderPublicKey),
			};
			multisignatureInfoToIndex.push(members);
		});
	return multisignatureInfoToIndex;
};
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]
Please consider the following remarks.

**Review by sameersubudhi — APPROVED** [review]
Thank you. LGTM 👍

**Review by MichalTuleja — APPROVED** [review]
