### PR TITLE
Fixed transaction date conversion - Closes #274

### LINKED ISSUE #274: Fix transaction date conversion
### Actual behavior

Timestamp returned from `/api/v1/transactions` endpoint is incorrect.

### Expected behavior

Timestamp returned from `/api/v1/transactions` endpoint is in a proper unix time format.

### Steps to reproduce

Retrieve `/api/v1/transactions`.

### Which version(s) does this affect? (Environment, OS, etc...)

`v0.2.0-beta.1`

### Additional information

Possible solution might a removal of the line

```
transaction.unixTimestamp = await coreApi.getUnixTime(transaction.timestamp)
```

from the following code:

```
			if (!transaction.timestamp) {
				const txBlock = (await getBlocks({ height: transaction.height })).data[0];
				transaction.timestamp = txBlock.unixTimestamp;
			}
			transaction.unixTimestamp = await coreApi.getUnixTime(transaction.timestamp);
			return transaction;
		},
```

### PR DESCRIPTION
**Pull request by nagdahimanshu**
### What was the problem?
This PR resolves #274 

### How was it solved?

- [x] Refactored transaction to parse timestamp properly for all version
- [x] Move timestamp conversion logic to compat layer

### How was it tested?
Local

### CODE REVIEW

**Review by sameersubudhi — APPROVED** [review]

File: services/core/shared/core/compat/sdk_v4/transactions.js [hunk 1]
```diff
@@ -61,6 +62,19 @@ const getTransactions = async params => {
 		if (response.meta) transactions.meta = response.meta;
 	}
 
+	transactions.data = await BluebirdPromise.map(
+		transactions.data,
+		async transaction => {
+			if (!transaction.timestamp) {
+				const txBlock = (await coreApi.getBlocks({ height: transaction.height })).data[0];
+				transaction.timestamp = txBlock.timestamp;
+			}
```
Comment (MichalTuleja) [inline services/core/shared/core/compat/sdk_v4/transactions.js:71]: Is there any case in SDKv4 that the transaction time is there already?

Comment (nagdahimanshu) [reply services/core/shared/core/compat/sdk_v4/transactions.js:71]: In case of (params.fromTimestamp ||  params.totimeStamp), we already resolve timestamp when we call function `getTransactionsByBlock`. So, just to avoid an unnecessary call i added this check.

```
	if (params.fromTimestamp || params.toTimestamp) {
		const blocks = await coreApi.getBlocks(params);
		transactions.meta.count = 0;
		await BluebirdPromise.map(
			blocks.data,
			async (block) => {
				const blkTransactions = await getTransactionsByBlock(block);
				transactions.data = transactions.data.concat(blkTransactions.data);
				transactions.meta.count += blkTransactions.meta.count;
			},
			{ concurrency: blocks.data.length },
		);
	}
```

**Review by MichalTuleja — APPROVED** [review]
