### PR TITLE
 Duplicate transactions returned

### LINKED ISSUE #1229: Duplicate transactions returned
### Actual behavior
Repeated transaction in the response even when queried with different offsets.

Eg: Transaction with ID `0557163513927ed2197ba9ddfbea20c39f62709ac49a4850991f0c7dea4d7e57` is present in the response for the following queries.

With offset 0:
https://service.lisk.com/api/v2/transactions?height=19365983&limit=10&offset=0&includePending=false

With offset 10:
https://service.lisk.com/api/v2/transactions?height=19365983&limit=10&offset=10&includePending=false

### Expected behavior

The transaction should appear in only one of the responses since the `offset` in the second query is greater than equal to the `limit` set in the first query.

### Steps to reproduce

- Query the above endpoints and check the transactions returned

### Which version(s) does this affect? (Environment, OS, etc...)
`v0.6.4`

### PR DESCRIPTION
**Pull request by sameersubudhi**
### What was the problem?
This PR resolves #1229 

### How was it solved?
- [x] Update Makefile to temporarily use `https://npm.lisk.com` registry
- [x] Sync latest framework dependencies
- [x] Update all the microservices to the latest framework version
- [x] Fix healthcheck script for MariaDB
- [x] Add `order` param support to MySQL implementation
- [x] Update `transactions` schema
- [x] Enforce `order: 'index:asc'` when querying transactions to ensure unique entries are returned from the index when queried with various pagination params
- [x] Update Jenkinsfile to use Lisk registry and perform cleanup post execution

### How was it tested?
Run Lisk Service against the Lisk Core v3.0.4 on Mainnet and query the specified endpoint on issue #1229.

### CODE REVIEW

File: services/core/shared/core/compat/sdk_v5/transactions.js [hunk 1]
```diff
@@ -72,10 +72,11 @@ const getTransactionIndexingInfo = async (blocks) => {
 	let multisignatureInfoToIndex = [];
 	const publicKeysToIndex = [];
 	const recipientAddressesToIndex = [];
-	const txnMultiArray = blocks.map(block => {
+	const txnMultiArray = blocks.map((block, index) => {
 		const transactions = block.payload.map(tx => {
 			const [{ id }] = availableLiskModuleAssets
 				.filter(module => module.id === String(tx.moduleID).concat(':').concat(tx.assetID));
+			tx.index = index;
```
Comment (priojeetpriyom) [inline services/core/shared/core/compat/sdk_v5/transactions.js:79]: why are we storing the index of block as index of transaction?

Comment (sameersubudhi) [reply services/core/shared/core/compat/sdk_v5/transactions.js:79]: Fixed!

File: framework/bin/socket_io_subscribe_client.js [hunk 2]
```diff
@@ -46,6 +46,7 @@ const subscribe = event => {
 	});
 };
 
+// subscribe('*'); // Listen to all the events
```
[the remark this answers is not in the document]
Comment (sameersubudhi) [reply framework/bin/socket_io_subscribe_client.js:49]: Because this is a blanket subscription and stated for user's convenience. The specific events are also stated below.

**Review by nagdahimanshu — APPROVED** [review]
LGTM 👍

**Review by priojeetpriyom — APPROVED** [review]
