### PR TITLE
Fix deadlock issues - Closes #1014

### LINKED ISSUE #1014: Mitigate database deadlocks for account updates
### Actual behavior

The database deadlocks are happening when multiple rows are updated at once. It happen usually when accounts and votes are updated.

### Expected behavior

Mitigate the database deadlocks by eliminating locks on multiple rows during updates.

### Steps to reproduce

1. Run the instance.
2. Start indexing.
3. Deadlocks will be reported in the console.

### Which version(s) does this affect? (Environment, OS, etc...)

Usually with Docker, esp. on a slower machine. M1-Macs are also suitable with Rosetta enabled.

### PR DESCRIPTION
**Pull request by MichalTuleja**
### What was the problem?
This PR resolves #1014

### How was it solved?

- [x] Added independent account queue
- [x] Added independent aggregate-related queues
- [x] Moved genesis block account indexing before the block index schedule
- [x] Moved aggregated values to an independent transaction
- [x] Reduced number of DB connections during updates

### How was it tested?

Linux

### CODE REVIEW

File: services/core/shared/core/compat/sdk_v5/paramUtils.js [hunk 1]
```diff
@@ -19,7 +19,12 @@ const {
...
-		const [from, to] = params[property].split(':');
+		const [fromStr, toStr] = params[property].split(':');
+
+		const from = Number(fromStr);
+		const to = Number(toStr);
+
+		if (Number.isNaN(from) || Number.isNaN(to)) throw new ValidationException(`Invalid (non-numeric) '${property}' range values supplied: ${params[property]}.`);
 		if (from && to && from > to) throw new ValidationException(`From ${property} cannot be greater than to ${property}.`);
 
 		if (!params.propBetweens) params.propBetweens = [];
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/paramUtils.js:30]: To support partial ranges (`100:` or `:100`) appropriately, please consider replacing the next line with the following. With the current changes, the unsupplied `to` or `from` defaults to `0`. Also, we'll need to add a couple of test cases corresponding to the suggested changes.

```
		params.propBetweens.push({ property, from, to });
```
to
```
		if (fromStr === '') {
			params.propBetweens.push({ property, to });
		} else if (toStr === '') {
			params.propBetweens.push({ property, from });
		} else {
			params.propBetweens.push({ property, from, to });
		}
```

File: services/core/shared/core/compat/sdk_v5/accounts.js [hunk 2]
```diff
@@ -321,6 +321,25 @@ const getAccountsByPublicKey = async (accountInfoArray) => {
 	return accounts;
 };
 
+const getAccountsByPublicKey2 = async (accountInfoArray) => {
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/accounts.js:324]: Do we need this method?
The method `getAccountsByPublicKey` has the exact same logic except that `accountInfoArray` is an array of objects containing the `publicKey` property.

File: services/core/shared/core/compat/sdk_v5/accountIndex.js [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+const getAccountIndex = () => getTableInstance('accounts', accountsIndexSchema);
+
+const updateAccountInfoPk = async (job) => {
+	const publicKey = job.data;
+
+	const account = await getAccountsByPublicKey2([publicKey]);
+	if (account.length) {
+		const accountsDB = await getAccountIndex();
+		await accountsDB.upsert(account);
+	}
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/accountIndex.js:44]: Please consider updating the variable name to `accounts` since `getAccountsByPublicKey2` returns an array of accounts.
```suggestion
	const accounts = await getAccountsByPublicKey2([publicKey]);
	if (accounts.length) {
		const accountsDB = await getAccountIndex();
		await accountsDB.upsert(accounts);
	}
```

File: services/core/shared/core/compat/sdk_v5/accountIndex.js [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+};
+
+const updateAccountInfoAddr = async (job) => {
+	const address = job.data;
+
+	const account = await getAccountsByAddress([address]);
+	if (account.length) {
+		const accountsDB = await getAccountIndex();
+		await accountsDB.upsert(account);
+	}
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/accountIndex.js:54]: Same as above.
```suggestion
	const accounts = await getAccountsByAddress([address]);
	if (accounts.length) {
		const accountsDB = await getAccountIndex();
		await accountsDB.upsert(accounts);
	}
```

File: services/core/shared/core/compat/sdk_v5/blockchainIndex.js [hunk 5]
```diff
@@ -130,124 +140,153 @@ const getGeneratorPkInfoArray = async (blocks) => {
...
+		if (KEY_BASED_ACCOUNT_UPDATE === true) {
+			const addresses = ensureArray(accountsFromTransactions)
+				.filter(a => a.publicKey).map(a => a.publicKey);
+			const publicKeys = ensureArray(accountsFromTransactions)
+				.filter(a => !a.publicKey).map(a => a.address);
+
+			blocks.forEach(block => indexAccountByPublicKey(block.generatorPublicKey));
+			publicKeys.forEach(pk => indexAccountByPublicKey(pk));
+			addresses.forEach(a => indexAccountByAddress(a));
+		}
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/blockchainIndex.js:254]: This code-block is never executed since `KEY_BASED_ACCOUNT_UPDATE` is defined as a constant and defaults to `false`.

File: services/core/shared/core/compat/sdk_v5/blockchainIndex.js [hunk 6]
```diff
@@ -694,16 +740,23 @@ const init = async () => {
...
 		// Start the indexing process (blocks)
 		await indexMissingBlocks();
 		await updateNonFinalBlocks();
 
-		// Start the indexing process (accounts)
-		await cacheLegacyAccountInfo();
-		await indexGenesisAccounts();
+		if (KEY_BASED_ACCOUNT_UPDATE === true) {
+			setInterval(triggerAccountUpdates, 15 * 1000); // ms
+		}
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/blockchainIndex.js:759]: Same as above.

**Review by sameersubudhi — CHANGES_REQUESTED** [review]
Please find my observations below.

**Comment by sameersubudhi** [comment]
Seeing the following errors/warnings in the logs. However, the process recovers after a while.
```
2022-04-04T12:24:07.011 ERROR [queue] indexAccountsQueue Job error,Error: Missing lock for job 2645221 retry
2022-04-04T12:24:07.011 ERROR [queue] indexAccountsQueue Job error,Error: Missing lock for job 2645222 retry
2022-04-04T12:24:07.012 INFO [dynamicFees] Recalulated dynamic fees: L: 0 M: 0 H: 0
2022-04-04T12:24:07.378 INFO [events] Registering ws://host.docker.internal:8080 for blockchain events
2022-04-04T12:24:36.751 WARN [BROKER] Request 'core.transactions' is timed out.,[object Object]
2022-04-04T12:24:40.543 WARN [BROKER] Request 'core.transactions' is timed out.,[object Object]
2022-04-04T12:25:06.423 INFO [blockchainIndex] currentChainHeight: 18177316, lastIndexedBlock: 18177317
2022-04-04T12:25:06.423 INFO [blockchainIndex] Block index status: 824269/1907024 blocks indexed (43.22%) 
2022-04-04T12:25:06.720 WARN [queue] indexAccountsQueue Job failed,Missing lock for job 2645224 finished
2022-04-04T12:25:06.720 WARN [queue] indexAccountsQueue Job failed,Error: Missing lock for job 2645224 finished
    at Object.finishedErrors (/home/lisk/lisk-service/core/node_modules/bull/lib/scripts.js:189:16)
    at /home/lisk/lisk-service/core/node_modules/bull/lib/scripts.js:176:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-04-04T12:25:06.720 INFO [queue] Queue counters: waiting: 842, active: 39, failed: 0, paused: 0
2022-04-04T12:25:06.830 WARN [queue] indexAccountsQueue Job failed,Missing lock for job 2645223 finished
2022-04-04T12:25:06.830 WARN [queue] indexAccountsQueue Job failed,Error: Missing lock for job 2645223 finished
    at Object.finishedErrors (/home/lisk/lisk-service/core/node_modules/bull/lib/scripts.js:189:16)
    at /home/lisk/lisk-service/core/node_modules/bull/lib/scripts.js:176:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-04-04T12:25:15.103 ERROR [mysql] Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
2022-04-04T12:25:15.122 ERROR [mysql] Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?


----

2022-04-04T12:29:06.886 WARN [queue] indexAccountsQueue Job failed,Promise timed out after 300000 milliseconds
2022-04-04T12:29:06.887 WARN [queue] indexAccountsQueue Job failed,TimeoutError: Promise timed out after 300000 milliseconds
    at Timeout._onTimeout (/home/lisk/lisk-service/core/node_modules/p-timeout/index.js:34:63)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)

```

File: services/core/shared/core/compat/sdk_v5/accounts.js (hunk 2 above)
Comment (MichalTuleja) [reply services/core/shared/core/compat/sdk_v5/accounts.js:324]: Technically not, however this will require to do more refactoring which is beyond the scope of that issue.

File: services/core/shared/core/compat/sdk_v5/blockchainIndex.js (hunk 5 above)
Comment (MichalTuleja) [reply services/core/shared/core/compat/sdk_v5/blockchainIndex.js:254]: That is correct, as it does the same as the logic above, but it does not entirely work. I would like to fix that code in the `0.7.x` branch.

File: services/core/shared/core/compat/sdk_v5/blockchainIndex.js (hunk 6 above)
Comment (MichalTuleja) [reply services/core/shared/core/compat/sdk_v5/blockchainIndex.js:759]: That code prevents from updating too many accounts at once but it needs to work with the logic mentioned above. So far there is a partial solution to that (working lists, but problems with the public key update) so it need more updates to enable it in production.

File: services/core/shared/core/compat/sdk_v5/paramUtils.js (hunk 1 above)
Comment (MichalTuleja) [reply services/core/shared/core/compat/sdk_v5/paramUtils.js:30]: @sameersubudhi Can you please provide the issue number?

Comment (sameersubudhi) [reply services/core/shared/core/compat/sdk_v5/paramUtils.js:30]: Created the following, with the exact information: https://github.com/LiskHQ/lisk-service/issues/1056

File: services/core/shared/core/compat/sdk_v5/accounts.js [hunk 7]
```diff
@@ -321,6 +321,25 @@ const getAccountsByPublicKey = async (accountInfoArray) => {
...
+			account.publicKey = accountInfo.publicKey;
+			account.username = account.dpos.delegate.username || null;
+			account.totalVotesReceived = account.dpos.delegate.totalVotesReceived;
+			account.balance = account.token.balance;
+			return account;
+		},
+		{ concurrency: 10 },
+	);
+	return accounts;
+};
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/accounts.js:341]:
```suggestion
const getAccountsByPublicKey2 = async (publicKeys) => {
	const accounts = await BluebirdPromise.map(
		publicKeys,
		async publicKey => {
			const address = getHexAddressFromPublicKey(publicKey);
			const { data: [account] } = await getAccountsFromCore({ address });
			account.publicKey = publicKey;
			account.username = account.dpos.delegate.username || null;
			account.totalVotesReceived = account.dpos.delegate.totalVotesReceived;
			account.balance = account.token.balance;
			return account;
		},
		{ concurrency: 10 },
	);
	return accounts;
};
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/core/shared/core/compat/sdk_v5/blockchainIndex.js [hunk 8]
```diff
@@ -130,124 +138,106 @@ const getGeneratorPkInfoArray = async (blocks) => {
...
-				? `Deadlock encountered while indexing block at height ${fromHeight}`
-				: `Deadlock encountered while indexing blocks in height range ${fromHeight} - ${toHeight}`;
-			throw new Error(`${errMessage}. Will retry later.`);
+			throw new Error(`Deadlock encountered while indexing block at height ${height}. Will retry later.`);
 		}
 		throw error;
 	}
 };
 
+
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/blockchainIndex.js:240]:
```suggestion
```

**Review by sameersubudhi — COMMENTED** [review]
Please find a couple more minor observations below.

File: services/core/shared/core/compat/sdk_v5/blockchainIndex.js [hunk 9]
```diff
@@ -130,124 +138,106 @@ const getGeneratorPkInfoArray = async (blocks) => {
 	return pkInfoArray;
 };
 
-const updateProducedBlocksAndRewards = async (generatorPkInfoArray, trx) => {
+const updateProducedBlocksAndRewards = async (pkInfoArray, trx) => {
```
[the remark this answers is not in the document]
Comment (MichalTuleja) [reply services/core/shared/core/compat/sdk_v5/blockchainIndex.js]: @sameersubudhi Updated. Can you please review it again?

[the remark this answers is not in the document]
Comment (sameersubudhi) [reply services/core/shared/core/compat/sdk_v5/blockchainIndex.js]: Thank you for the changes. They look good. Currently, testing against the mainnet (with indexing about 40% through) encountered the following errors a few times but they do not seem to be serious as no job failures have been recorded so far. Also, the public keys are now getting indexed 🎉 

```
2022-04-14T12:18:00.841 WARN [DISCOVERY] Heartbeat is not received from '963ce85d5320-1' node.
2022-04-14T12:18:00.842 WARN [REGISTRY] Node '963ce85d5320-1' disconnected unexpectedly.
2022-04-14T12:18:00.850 INFO [queue] Queue counters: waiting: 27550, active: 41, failed: 0, paused: 0
2022-04-14T12:18:00.977 INFO [REGISTRY] Node '963ce85d5320-1' reconnected.
2022-04-14T12:18:00.982 INFO [REGISTRY] Node '226391f0783c-1' reconnected.
2022-04-14T12:18:00.984 INFO [REGISTRY] Node '60c6ab5ff273-1' reconnected.
2022-04-14T12:18:00.991 INFO [REGISTRY] Node 'c2e5c4bb0a43-1' reconnected.
2022-04-14T12:18:01.120 ERROR [queue] indexAccountsQueue Job error,Error: Missing lock for job 1097420 retry
2022-04-14T12:18:01.121 ERROR [queue] indexAccountsQueue Job error,Error: Missing lock for job 1097341 retry
```

File: services/core/shared/core/compat/sdk_v5/blockchainIndex.js [hunk 10]
```diff
@@ -102,6 +106,10 @@ const getIndexVerifiedHeight = () => blockchainStore.get('indexVerifiedHeight');
 const setIndexDiff = (height) => blockchainStore.set('indexStatus', height);
 const getIndexDiff = () => blockchainStore.get('indexStatus');
 
+// Key-based account update
+// There is a bug that does not update public keys
+const KEY_BASED_ACCOUNT_UPDATE = false;
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/blockchainIndex.js:111]: Now that the public keys are getting indexed, do we want to enable this?

Comment (MichalTuleja) [reply services/core/shared/core/compat/sdk_v5/blockchainIndex.js:111]: I would prefer to enable it in a different PR.

**Review by sameersubudhi — APPROVED** [review]
The logs show intermittent Knex timeout errors. These errors are non-critical since the application recovers and the indexing process achieves 100%. We can address them in a separate issue.

**Review by nagdahimanshu — APPROVED** [review]
