### PR TITLE
Fix missing produced blocks and rewards - Closes #455

### LINKED ISSUE #455: Fix missing producedBlocks and rewards
### Actual behavior

The properties `producedBlocks` and `rewards` are missing.

### Expected behavior

Make missing properties work in the account response.

### Steps to reproduce

Request a delegate account details.

### PR DESCRIPTION
**Pull request by nagdahimanshu**
### What was the problem?
This PR resolves #455

### How was it solved?
- [x] Implement `increment`  method in `mysql`
- [x] Increment `rewards` and `producedBlocks` on every new block
- [x] Add check to increment only for forgers accounts
- [x] Support for setting `default` values in DB `mysql`

### How was it tested?
- [x] Local
- [x] No Performance issues
- [x] Jenkins

### CODE REVIEW

**Review by MichalTuleja — APPROVED** [review]

File: services/core/shared/core/compat/sdk_v5/schema/accounts.js [hunk 1]
```diff
@@ -21,8 +21,8 @@ module.exports = {
 		isDelegate: { type: 'boolean' },
 		balance: { type: 'bigInteger' },
 		username: { type: 'string' },
-		rewards: { type: 'bigInteger' },
-		producedBlocks: { type: 'integer' },
+		rewards: { type: 'bigInteger', default: true, defaultValue: 0 },
+		producedBlocks: { type: 'integer', default: true, defaultValue: 0 },
```
Comment (sameersubudhi) [inline services/core/shared/core/compat/sdk_v5/schema/accounts.js:25]: We can remove the `default` params below and update `mysql.js` as below.
This would help us keep the schema pollution-free (i.e no non-knex related configs).

```suggestion
		rewards: { type: 'bigInteger', defaultValue: 0 },
		producedBlocks: { type: 'integer', defaultValue: 0 },
```

File: services/core/shared/indexdb/mysql.js [hunk 2]
```diff
@@ -35,6 +35,7 @@ const loadSchema = async (knex, tableName, tableConfig) => {
 			Object.keys(schema).map(p => {
 				const kProp = (table[schema[p].type])(p);
 				if (schema[p].null === false) kProp.notNullable();
+				if (schema[p].default) kProp.defaultTo(schema[p].defaultValue);
```
Comment (sameersubudhi) [inline services/core/shared/indexdb/mysql.js:38]:
```suggestion
				if ('defaultValue' in schema[p]) kProp.defaultTo(schema[p].defaultValue);
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]
Please find my review suggestion below.

**Review by sameersubudhi — APPROVED** [review]
