### PR TITLE
Block ID present in pending transactions

### LINKED ISSUE #1664: Block ID present in pending transactions
### Actual behavior

Querying `/transactions?executionStatus=pending` endpoint returns transactions with `block.id` (transactionID itself).

```
{
  "data": [
    {
      "id": "8d9c3b39fd7a74917357226bccd876215656f89dd987e52408e89c815a119c5d",
      "moduleCommand": "pos:stake",
      "nonce": "2",
      "fee": "153000",
      "minFee": "151000",
      "size": 151,
      "sender": {
        "address": "lskmz22uzabdhhad2ddb2f6hqky9v9b4n926hggfg",
        "publicKey": "527dbb5cecbf080d2079f6f193a89514cfbe1f5804ac2afee040c98d85ea4548",
        "name": "korben3"
      },
      "params": {
        "stakes": [
          {
            "validatorAddress": "lskmz22uzabdhhad2ddb2f6hqky9v9b4n926hggfg",
            "amount": "1000000000000"
          }
        ]
      },
      "block": {
        "id": "8d9c3b39fd7a74917357226bccd876215656f89dd987e52408e89c815a119c5d"
      },
      "executionStatus": "pending"
    }
  ],
  "meta": {
    "count": 4,
    "offset": 0,
    "total": 4
  }
}
```

### Expected behavior

Pending transactions shouldn't contain blockID.

### Steps to reproduce

- Post a transaction with nonce than the actual nonce
- Query the `/transactions?executionStatus=pending` endpoint

### Which version(s) does this affect? (Environment, OS, etc...)

v0.7.0-beta.1

### PR DESCRIPTION
**Pull request by priojeetpriyom**
### What was the problem?
This PR resolves #1664 

### How was it solved?
- [x] Fix blockID present in pending transactions response
- [x] Fix empty object is not returned in response & update tests
- [x] Remove `links` from existing response schemas 
- [x] **breaking change** : mark `block` as optional in response of `transactions` api 
### How was it tested?
- [x] Local

### CODE REVIEW

**Comment by nagdahimanshu** [comment]
Looks good but block object is not available in the pending transactions response. Response should contain empty block object. Can you confirm @sameersubudhi?

File: services/gateway/shared/customMapper.js [hunk 1]
```diff
@@ -70,6 +73,7 @@ const mapObject = (rootObj, definition, subObj = rootObj) => Object.keys(definit
 			const tempObj = mapObject(rootObj, definition[key], subObj[key]);
 			const values = Object.values(tempObj);
 			if (objWithValues(values) && validate(tempObj)) acc[key] = tempObj;
```
Comment (vardan10) [inline services/gateway/shared/customMapper.js:75]: We can remove `validate` function since `objWithValues` function already takes care of it.
```suggestion
			if (objWithValues(values)) acc[key] = tempObj;
```

**Review by vardan10 — COMMENTED** [review]
Changes looks good and works as expected.
But they introduce empty `links` object in all API modules except POS. Should we remove it or update the swagger for the same?

File: services/gateway/shared/customMapper.js (hunk 1 above)
Comment (priojeetpriyom) [reply services/gateway/shared/customMapper.js]: Nice catch 💯 Applied both.

**Review by vardan10 — APPROVED** [review]

**Review by sameersubudhi — COMMENTED** [review]
Please add a separate schema for the pending transactions in the tests. And, please adjust the existing testcases accordingly.

**Comment by priojeetpriyom** [comment]
> Please add a separate schema for the pending transactions in the tests. And, please adjust the existing testcases accordingly.

Applied.

**Review by sameersubudhi — APPROVED** [review]

File: tests/integration/api_v3/http/transactions.test.js [hunk 2]
```diff
@@ -528,20 +546,20 @@ describe('Transactions API', () => {
...
 
-		it('returns 400 BAD REQUEST with unsupported params', async () => {
+		it('should throw error when called with unsupported params', async () => {
 			const expectedStatusCode = 400;
 			const response = await api.get(`${endpoint}?address=${refTransaction.sender.address}&nonce=${Number(refTransaction.nonce) - 1}`, expectedStatusCode);
 			expect(response).toMap(badRequestSchema);
 		});
 
-		it('returns 200 OK when queried with transactionID and non-zero offset', async () => {
+		it('should throw error when queried with transactionID and non-zero offset', async () => {
```
Comment (vardan10) [inline tests/integration/api_v3/http/transactions.test.js:555]: Just to maintain consistency.
```suggestion
		it('should throw error when called with transactionID and non-zero offset', async () => {
```

**Review by vardan10 — APPROVED** [review]
