### PR TITLE
Transaction estimate fees throws an error on the sidechain

### LINKED ISSUE #1843: Transaction estimate fees throws an error on the sidechain
### Actual behavior
Currently, transaction estimate fees throws an error on the sidechain:
```
{
    "error": true,
    "message": "Server error: The number NaN cannot be converted to a BigInt because it is not an integer"
}

```

### Expected behavior
Transaction estimate fees should return estimated fees without any issues on the sidechain

### Steps to reproduce

- Invoke the `/transactions/estimate-fees` endpoint on sidechain

### Which version(s) does this affect? (Environment, OS, etc...)
v0.7.0-rc.0

### PR DESCRIPTION
**Pull request by nagdahimanshu**
### What was the problem?
This PR resolves #1843 #1849 

### How was it solved?

- [x] Set default value for minFeePerByte
- [x] Refactor `resolveChannelInfo` method and add extra checks
- [x] Calculate escrow initialisation fees only when token transfer is a native token
- [x] Code refactoring

### How was it tested?
Local

### CODE REVIEW

File: services/blockchain-indexer/shared/dataService/business/interoperability/chain.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+ */
+const { getNetworkStatus } = require('../network');
+const regex = require('../../../regex');
+
+let chainID;
+
+const isMainchain = async () => {
+	if (!chainID) {
+		const networkStatus = (await getNetworkStatus()).data;
+		chainID = networkStatus.chainID;
```
Comment (vardan10) [inline services/blockchain-indexer/shared/dataService/business/interoperability/chain.js:24]:
```suggestion
		await getCurrentChainID();
```

File: services/blockchain-indexer/shared/dataService/business/interoperability/chain.js [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+	}
+	return regex.MAINCHAIN_ID.test(chainID);
+};
+
+const getCurrentChainID = async () => {
+	if (!chainID) {
+		const networkStatus = (await getNetworkStatus()).data;
+		chainID = networkStatus.chainID;
```
Comment (vardan10) [inline services/blockchain-indexer/shared/dataService/business/interoperability/chain.js:32]: This might help to avoid runtime errors?
```suggestion
		const networkStatus = await getNetworkStatus();
		if(networkStatus.data && networkStatus.data.chainID) {
		    chainID = networkStatus.chainID;
		}
```

File: services/blockchain-indexer/tests/unit/shared/dataservice/business/interoperability/channel.test.js [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+const mockedFilePath = resolve(`${__dirname}/../../../../../../shared/dataService/business/network`);
+const dataServicePath = resolve(`${__dirname}/../../../../../../shared/dataService`);
+const mockedRequestFilePath = resolve(`${__dirname}/../../../../../../shared/utils/request`);
+
+const { mockChannelInfo } = require('../../../constants/transactionEstimateFees');
+
+beforeEach(() => {
+	jest.resetModules();
+
+	jest.mock('lisk-service-framework', () => {
```
Comment (vardan10) [inline services/blockchain-indexer/tests/unit/shared/dataservice/business/interoperability/channel.test.js:29]: I think we can declare this on top instead of executing it before every testcase.

File: services/blockchain-indexer/tests/unit/shared/dataservice/business/interoperability/chain.test.js [hunk 4]
```diff
@@ -139,58 +138,21 @@ describe('Test isMainchain method', () => {
 	});
 });
 
-describe('Test resolveMainchainServiceURL method', () => {
-	it('should return devnet mainchain URL when devnet mainchain chainID is valid', async () => {
-		const chainID = '04000000';
+describe('Test getCurrentChainID method', () => {
```
Comment (vardan10) [inline services/blockchain-indexer/tests/unit/shared/dataservice/business/interoperability/chain.test.js:141]: Should we add a testcase if `getNetworkStatus` throws error?

File: services/blockchain-indexer/shared/dataService/business/interoperability/chain.js [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+
+let chainID;
+
+const isMainchain = async () => {
+	if (!chainID) {
+		const networkStatus = (await getNetworkStatus()).data;
+		chainID = networkStatus.chainID;
+	}
+	return regex.MAINCHAIN_ID.test(chainID);
+};
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/business/interoperability/chain.js:27]: Would it be better to simplify like below

```suggestion
const isMainchain = async () => regex.MAINCHAIN_ID.test(await getCurrentChainID());
```

**Review by vardan10 — APPROVED** [review]

**Review by priojeetpriyom — APPROVED** [review]
