### PR TITLE
Fix delegate rank calculation - Closes #638

### LINKED ISSUE #638: Fix incorrect delegate rank calculation
### Actual behavior 
Delegate property 'rank' is not calculated properly

### Expected behavior
Delegate rank should be calculated on every new block and return correct delegate list

### Steps to reproduce
Run Lisk Service on local and check the rank of delegates

### Which version(s) does this affect? (Environment, OS, etc...)
0.4.0

### PR DESCRIPTION
**Pull request by nagdahimanshu**
### What was the problem?
This PR resolves #638 

### How was it solved?
- [x] Implemented logic to update only specific delegates which get updated on every block (instead of updating the whole list)
- [x] Update cron job to schedule `reloadDelegatesCache` in every 5 minutes
- [x] Add sleep in Jenkinsfile
- [x] Support for special character `MySQL` in core service
 
### How was it tested?
Local + Jenkins

### CODE REVIEW

File: services/core/shared/core/delegates.js [hunk 1]
```diff
@@ -249,6 +249,34 @@ const reload = async () => {
...
+			if (indexOfDelegate === -1) {
+				delegateList.push(delegate);
+			} else {
+				delegateList[indexOfDelegate] = delegate;
+			}
+		});
+		await computeDelegateRank();
+		await computeDelegateStatus();
+	}
+});
```
Comment (sameersubudhi) [inline services/core/shared/core/delegates.js:278]: Delegate `rank` would vary only when the `voteWeight` changes and the `status` gets updated at the beginning of a new round. 

```suggestion
// Keep the delegate cache up-to-date
Signals.get('newBlock').add(async data => {
	const dposModuleId = 5;
	const voteDelegateAssetId = 1;

	const updatedDelegateAddresses = [];

	const [block] = data.data;
	if (block && block.payload) {
		block.payload.forEach(tx => {
			if (tx.moduleID === dposModuleId && tx.assetID === voteDelegateAssetId) {
				tx.asset.votes.forEach(vote => updatedDelegateAddresses
					.push(coreApi.getBase32AddressFromHex(vote.delegateAddress)));
			}
		});

		const { data: updatedDelegateAccounts } = await coreApi
			.getAccounts({ addresses: updatedDelegateAddresses });

		updatedDelegateAccounts.forEach(delegate => {
			const delegateIndex = delegateList.findIndex(acc => acc.address === delegate.address);
			if (delegateIndex === -1) delegateList.push(delegate);
			else delegateList[delegateIndex] = delegate;
		});

		// Rank is impacted only when a delegate gets (un-)voted
		if (updatedDelegateAddresses.length) await computeDelegateRank();
	}
});
```

**Review by sameersubudhi — CHANGES_REQUESTED** [review]
Please find my review.

**Review by MichalTuleja — APPROVED** [review]

**Review by sameersubudhi — APPROVED** [review]
LGTM 👍
