### PR TITLE
Event API takes a long time to return result when queried with topics 

### LINKED ISSUE #1952: Event API takes a long time to return result when queried with topics
### Actual behavior
Event API takes a long time to return result when queried with topics

### Expected behavior
Event API should be optimised to deliver a better performance.

### Steps to reproduce
Query this endpoint:
https://testnet-service.lisk.com/api/v3/events?offset=100&limit=100&topic=lskwtb4oevaa4jtb5q66fs4oqkac4gn9r6huehk5d

### Which version(s) does this affect? (Environment, OS, etc...)
v0.7.0-rc.5

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1952 

### How was it solved?
- [x] Used joins to speed up db query
- [x] Updated gateway to only allow topics with min length 3

### How was it tested?
Local + testnet

### CODE REVIEW

File: services/blockchain-indexer/shared/dataService/business/events.js [hunk 1]
```diff
@@ -176,42 +196,43 @@ const getEvents = async params => {
...
-				topics.push(t.slice(EVENT_TOPIC_PREFIX.TX_ID.length));
-			} else if (
-				t.startsWith(EVENT_TOPIC_PREFIX.CCM_ID) &&
-				t.length === EVENT_TOPIC_PREFIX.CCM_ID.length + LENGTH_ID
-			) {
-				// Check for CCM ID both with and without the topic prefix
-				topics.push(t.slice(EVENT_TOPIC_PREFIX.CCM_ID.length));
-			}
+		const allTopics = topic.split(',');
+		if (topic.length === LENGTH_ID) {
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/dataService/business/events.js:200]: This entire if..else ladder needs to be within a for loop against the allTopics.

**Review by sameersubudhi — CHANGES_REQUESTED** [review]
Everything else except the below looks good to me. Can we please fix this ASAP.

File: services/blockchain-indexer/shared/dataService/business/events.js [hunk 2]
```diff
@@ -224,10 +248,10 @@ const getEvents = async params => {
...
 			}
 
-			const [{ id, timestamp } = {}] = await blocksTable.find({ height, limit: 1 }, [
-				'id',
-				'timestamp',
-			]);
+			if (!blocksCache[height]) {
+				blocksCache[height] = await blocksTable.find({ height, limit: 1 }, ['id', 'timestamp']);
+			}
+			const [{ id, timestamp } = {}] = blocksCache[height];
```
Comment (priojeetpriyom) [inline services/blockchain-indexer/shared/dataService/business/events.js:254]: Why do we need this? As height is indexed, this should be cheap operation. Also, this can produce inconsistent results when fork happens for a height.

Comment (sameersubudhi) [reply services/blockchain-indexer/shared/dataService/business/events.js:254]: It was added last night when we were debugging and optimizing the code. But it's also fine if we remove this caching.

**Review by priojeetpriyom — APPROVED** [review]

**Review by sameersubudhi — APPROVED** [review]
LGTM and works as expected 👍

**Review by nagdahimanshu — APPROVED** [review]
