### PR TITLE
Consider transaction execution status within the hooks

### LINKED ISSUE #1678: Consider transaction execution status within the hooks
### Actual behavior

Currently, all the logic within the applyTransaction and revertTransaction hooks are executed without the consideration for the execution status.

### Expected behavior

The logic dependent on execution status must be executed accordingly.

### Steps to reproduce

- Check the transaction hook implementation for all the commands

### Which version(s) does this affect? (Environment, OS, etc...)

v0.7.0-beta.1

### PR DESCRIPTION
**Pull request by vardan10**
### What was the problem?
This PR resolves #1678 

### How was it solved?
- [x] By checking transaction status for all hooks

### How was it tested?
- [x] Local

### CODE REVIEW

File: services/blockchain-indexer/shared/indexer/blockchainIndex.js [hunk 1]
```diff
@@ -255,8 +255,13 @@ const deleteIndexedBlocks = async job => {
 						transactions,
 						async (tx) => {
 							// Invoke 'revertTransaction' to execute command specific reverting logic
-							await revertTransaction(blockHeader, tx, events, dbTrx);
 							const normalizedTransaction = await normalizeTransaction(tx);
+
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/blockchainIndex.js]: On L247, we can directly fetch all the transactions by blockID using the `getTransactionsByBlockID` method defined in `services/blockchain-indexer/shared/dataService/business/transactions.js`.

Also on L249, we need to fetch the events from the cache determined by the blockID instead of the blockHeight since the node will have replaced the events corresponding the new block at the same height.

File: services/blockchain-indexer/shared/indexer/transactionProcessor/auth/registerMultisignature.js [hunk 2]
```diff
@@ -45,16 +47,20 @@ const resolveMultisignatureMemberships = (tx) => {
...
 
 	return multisignatureInfoToIndex;
 };
 
 // eslint-disable-next-line no-unused-vars
 const applyTransaction = async (blockHeader, tx, events, dbTrx) => {
+	tx.params.mandatoryKeys.concat(tx.params.optionalKeys).forEach(key => {
+		// Asynchronously index all the publicKeys
+		updateAccountPublicKey(key);
+	});
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/transactionProcessor/auth/registerMultisignature.js:60]: To avoid looping through the `optionalKeys` over again.
```suggestion
	// Asynchronously index all the publicKeys
	tx.params.mandatoryKeys.forEach(updateAccountPublicKey);
	tx.params.optionalKeys.forEach(updateAccountPublicKey);
```

File: services/blockchain-indexer/shared/indexer/transactionProcessor/auth/registerMultisignature.js [hunk 3]
```diff
@@ -65,6 +71,13 @@ const applyTransaction = async (blockHeader, tx, events, dbTrx) => {
 
 // eslint-disable-next-line no-unused-vars
 const revertTransaction = async (blockHeader, tx, events, dbTrx) => {
+	tx.params.mandatoryKeys.concat(tx.params.optionalKeys).forEach(key => {
+		// Asynchronously index all the publicKeys
+		updateAccountPublicKey(key);
+	});
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/transactionProcessor/auth/registerMultisignature.js:77]:
```suggestion
	// Asynchronously index all the publicKeys
	tx.params.mandatoryKeys.forEach(updateAccountPublicKey);
	tx.params.optionalKeys.forEach(updateAccountPublicKey);
```

File: services/blockchain-indexer/shared/indexer/transactionProcessor/token/transfer.js
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/transactionProcessor/token/transfer.js:1]: Let's update the account index with the `recipientAddress`. Also, we'll need to check the logic for the balance updates.

File: services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js:1]: Same as above.

File: services/blockchain-indexer/shared/indexer/blockchainIndex.js [hunk 4]
```diff
@@ -245,21 +246,24 @@ const deleteIndexedBlocks = async job => {
 			blocks,
 			async block => {
 				let forkedTransactions;
+
+				const { data: transactions } = await getTransactionsByBlockID(block.id);
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/blockchainIndex.js:250]: Why don't we directly assign it to `forkedTransactions`?

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/blockchain-indexer/shared/indexer/blockchainIndex.js (hunk 1 above)
Comment (vardan10) [reply services/blockchain-indexer/shared/indexer/blockchainIndex.js]: Applied on L247.
Currently we dont support getting events by blockID so it will be handled in separate issue.

File: services/blockchain-indexer/shared/indexer/blockchainIndex.js [hunk 5]
```diff
@@ -244,22 +245,23 @@ const deleteIndexedBlocks = async job => {
 		await BluebirdPromise.map(
 			blocks,
 			async block => {
-				let forkedTransactions;
+				let { data: forkedTransactions } = await getTransactionsByBlockID(block.id);
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/blockchainIndex.js:248]:
```suggestion
				const { data: forkedTransactions } = await getTransactionsByBlockID(block.id);
```

File: services/blockchain-indexer/shared/indexer/blockchainIndex.js [hunk 6]
```diff
@@ -244,22 +245,23 @@ const deleteIndexedBlocks = async job => {
...
 				const transactionsTable = await getTransactionsTable();
 				const events = await getEventsByHeight(block.height);
 
-				if (block.transactions && block.transactions.length) {
-					const { transactions, assets, ...blockHeader } = block;
+				if (forkedTransactions && forkedTransactions.length) {
+					const { assets, ...blockHeader } = block;
 
 					forkedTransactions = await BluebirdPromise.map(
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/blockchainIndex.js:255]:
```suggestion
					await BluebirdPromise.map(
```

File: services/blockchain-indexer/shared/indexer/blockchainIndex.js [hunk 7]
```diff
@@ -244,22 +245,23 @@ const deleteIndexedBlocks = async job => {
...
-						transactions,
+						forkedTransactions,
 						async (tx) => {
 							// Invoke 'revertTransaction' to execute command specific reverting logic
 							await revertTransaction(blockHeader, tx, events, dbTrx);
+
 							const normalizedTransaction = await normalizeTransaction(tx);
 							return normalizedTransaction;
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/blockchainIndex.js:262]: `getTransactionsByBlockID` already normalizes.
```suggestion
```

File: services/blockchain-indexer/shared/indexer/blockchainIndex.js [hunk 8]
```diff
@@ -244,22 +245,23 @@ const deleteIndexedBlocks = async job => {
...
 						},
-						{ concurrency: block.transactions.length },
+						{ concurrency: forkedTransactions.length },
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/blockchainIndex.js:264]:
```suggestion
						{ concurrency: 1 },
```

File: services/blockchain-indexer/shared/indexer/transactionProcessor/token/transfer.js [hunk 9]
```diff
@@ -34,6 +38,10 @@ const COMMAND_NAME = 'transfer';
 
 // eslint-disable-next-line no-unused-vars
 const applyTransaction = async (blockHeader, tx, events, dbTrx) => {
+	indexAccountByAddress(tx.params.recipientAddress);
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/transactionProcessor/token/transfer.js:41]: L53-L56 seem redundant and can be removed. Also, the revert hook should also be updating both the accounts/transactionsTable.

File: services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js [hunk 10]
```diff
@@ -34,6 +38,10 @@ const COMMAND_NAME = 'transferCrossChain';
 
 // eslint-disable-next-line no-unused-vars
 const applyTransaction = async (blockHeader, tx, events, dbTrx) => {
+	indexAccountByAddress(tx.params.recipientAddress);
```
Comment (sameersubudhi) [inline services/blockchain-indexer/shared/indexer/transactionProcessor/token/transferCrossChain.js:41]: Same as above.

**Review by sameersubudhi — CHANGES_REQUESTED** [review]

File: services/blockchain-indexer/shared/indexer/blockchainIndex.js (hunk 5 above)
Comment (vardan10) [reply services/blockchain-indexer/shared/indexer/blockchainIndex.js:248]: It cannot be const since we are filtering null transactions here:
https://github.com/LiskHQ/lisk-service/blob/1678-consider-transaction-execution-status-within-the-hooks/services/blockchain-indexer/shared/indexer/blockchainIndex.js#L278

**Review by sameersubudhi — APPROVED** [review]

**Review by nagdahimanshu — APPROVED** [review]
LGTM and works as expected 👍
