### PR TITLE
Sorting by amount returns null values - Closes #499

### LINKED ISSUE #499: Sorting by amount returns null values
### Actual behavior

Sorting by amount returns null values.

### Expected behavior

Sorting by amount returns only non-null values.

### Steps to reproduce

Retrieve transactions sorted by amounts.

### PR DESCRIPTION
**Pull request by sameersubudhi**
### What was the problem?
This PR resolves #499 

### How was it solved?
- [x] Perform sorting only on non-null values
- [x] Merge sorting based test cases from PR https://github.com/LiskHQ/lisk-service/pull/497
- [x] Enable disabled transactions test cases 
- [x] Ensure `startHeight` is not lower than `genesisHeight` when checking for missing blocks

### How was it tested?
Local + Jenkins

### CODE REVIEW

File: services/core/shared/indexdb/mysql.js [hunk 1]
```diff
@@ -214,6 +214,7 @@ const getDbInstance = async (tableName, tableConfig, connEndpoint = config.endpo
 		if (params.sort) {
 			const [sortProp, sortOrder] = params.sort.split(':');
 			query.orderBy(sortProp, sortOrder);
+			query.whereNotNull(sortProp);
```
Comment (nagdahimanshu) [inline services/core/shared/indexdb/mysql.js:217]: It works well but returns incorrect count. Now, we need to add given logic to our count function as well to get exact count: 
```
if (params.sort) {
  const [sortProp, sortOrder] = params.sort.split(':');
  query.orderBy(sortProp, sortOrder);
  query.whereNotNull(sortProp);
}
```

**Review by nagdahimanshu — CHANGES_REQUESTED** [review]
Please consider one suggestion!

**Review by nagdahimanshu — APPROVED** [review]
LGTM!

**Review by MichalTuleja — APPROVED** [review]
LGTM 👍
